/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../index";

/**
 * @example
 *     {
 *         body: {
 *             inputValues: [{
 *                     type: "STRING",
 *                     name: "x"
 *                 }, {
 *                     type: "STRING",
 *                     name: "x"
 *                 }],
 *             evaluationValues: [{
 *                     type: "STRING",
 *                     name: "x"
 *                 }, {
 *                     type: "STRING",
 *                     name: "x"
 *                 }]
 *         }
 *     }
 */
export interface UpsertTestSuiteTestCaseRequest {
    body: Vellum.UpsertTestSuiteTestCaseRequestBody;
}
