/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface PatchedDeploymentReleaseTagUpdateRequest {
    /** The ID of the Release to tag */
    historyItemId?: string;
}
