/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vellum from "../../../../api/index";
import * as core from "../../../../core";

export const DeploymentsListRequestStatus: core.serialization.Schema<
    serializers.DeploymentsListRequestStatus.Raw,
    Vellum.DeploymentsListRequestStatus
> = core.serialization.enum_(["ACTIVE", "ARCHIVED", "PENDING_DELETION"]);

export declare namespace DeploymentsListRequestStatus {
    export type Raw = "ACTIVE" | "ARCHIVED" | "PENDING_DELETION";
}
