/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Vellum from "../../../../../api/index";
import * as core from "../../../../../core";

export const SerializeWorkflowFilesRequest: core.serialization.Schema<
    serializers.SerializeWorkflowFilesRequest.Raw,
    Vellum.SerializeWorkflowFilesRequest
> = core.serialization.object({
    files: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace SerializeWorkflowFilesRequest {
    export interface Raw {
        files: Record<string, unknown>;
    }
}
