/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Vellum from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Integrations {
    export interface Options {
        environment?: core.Supplier<environments.VellumEnvironment | environments.VellumEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Override the X-API-Version header */
        apiVersion?: core.Supplier<Vellum.ApiVersionEnum | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-API-Version header */
        apiVersion?: Vellum.ApiVersionEnum | undefined;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Integrations {
    constructor(protected readonly _options: Integrations.Options) {}

    /**
     * @param {string} integrationName - The integration name
     * @param {string} integrationProvider - The integration provider name
     * @param {string} toolName - The tool's unique name, as specified by the integration provider
     * @param {Vellum.RetrieveIntegrationToolDefinitionRequest} request
     * @param {Integrations.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vellum.NotFoundError}
     *
     * @example
     *     await client.integrations.retrieveIntegrationToolDefinition("integration_name", "integration_provider", "tool_name")
     */
    public retrieveIntegrationToolDefinition(
        integrationName: string,
        integrationProvider: string,
        toolName: string,
        request: Vellum.RetrieveIntegrationToolDefinitionRequest = {},
        requestOptions?: Integrations.RequestOptions,
    ): core.HttpResponsePromise<Vellum.ComponentsSchemasComposioToolDefinition> {
        return core.HttpResponsePromise.fromPromise(
            this.__retrieveIntegrationToolDefinition(
                integrationName,
                integrationProvider,
                toolName,
                request,
                requestOptions,
            ),
        );
    }

    private async __retrieveIntegrationToolDefinition(
        integrationName: string,
        integrationProvider: string,
        toolName: string,
        request: Vellum.RetrieveIntegrationToolDefinitionRequest = {},
        requestOptions?: Integrations.RequestOptions,
    ): Promise<core.WithRawResponse<Vellum.ComponentsSchemasComposioToolDefinition>> {
        const { toolkitVersion } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (toolkitVersion !== undefined) {
            _queryParams["toolkit_version"] = toolkitVersion;
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.VellumEnvironment.Production)
                        .default,
                `integrations/v1/providers/${encodeURIComponent(integrationProvider)}/integrations/${encodeURIComponent(integrationName)}/tools/${encodeURIComponent(toolName)}`,
            ),
            method: "GET",
            headers: {
                "X-API-Version":
                    (await core.Supplier.get(this._options.apiVersion)) != null
                        ? serializers.ApiVersionEnum.jsonOrThrow(await core.Supplier.get(this._options.apiVersion), {
                              unrecognizedObjectKeys: "strip",
                          })
                        : "2025-07-30",
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "vellum-ai",
                "X-Fern-SDK-Version": "1.12.2",
                "User-Agent": "vellum-ai/1.12.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : undefined,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ComponentsSchemasComposioToolDefinition.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vellum.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.VellumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VellumError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VellumTimeoutError(
                    "Timeout exceeded when calling GET /integrations/v1/providers/{integration_provider}/integrations/{integration_name}/tools/{tool_name}.",
                );
            case "unknown":
                throw new errors.VellumError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} integrationName - The integration name
     * @param {string} integrationProvider - The integration provider name
     * @param {string} toolName - The tool's unique name, as specified by the integration provider
     * @param {Vellum.ComponentsSchemasComposioExecuteToolRequest} request
     * @param {Integrations.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vellum.BadRequestError}
     * @throws {@link Vellum.ForbiddenError}
     * @throws {@link Vellum.NotFoundError}
     *
     * @example
     *     await client.integrations.executeIntegrationTool("integration_name", "integration_provider", "tool_name", {
     *         provider: "COMPOSIO",
     *         arguments: {
     *             "arguments": {
     *                 "key": "value"
     *             }
     *         }
     *     })
     */
    public executeIntegrationTool(
        integrationName: string,
        integrationProvider: string,
        toolName: string,
        request: Vellum.ComponentsSchemasComposioExecuteToolRequest,
        requestOptions?: Integrations.RequestOptions,
    ): core.HttpResponsePromise<Vellum.ComponentsSchemasComposioExecuteToolResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__executeIntegrationTool(integrationName, integrationProvider, toolName, request, requestOptions),
        );
    }

    private async __executeIntegrationTool(
        integrationName: string,
        integrationProvider: string,
        toolName: string,
        request: Vellum.ComponentsSchemasComposioExecuteToolRequest,
        requestOptions?: Integrations.RequestOptions,
    ): Promise<core.WithRawResponse<Vellum.ComponentsSchemasComposioExecuteToolResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.VellumEnvironment.Production)
                        .default,
                `integrations/v1/providers/${encodeURIComponent(integrationProvider)}/integrations/${encodeURIComponent(integrationName)}/tools/${encodeURIComponent(toolName)}/execute`,
            ),
            method: "POST",
            headers: {
                "X-API-Version":
                    (await core.Supplier.get(this._options.apiVersion)) != null
                        ? serializers.ApiVersionEnum.jsonOrThrow(await core.Supplier.get(this._options.apiVersion), {
                              unrecognizedObjectKeys: "strip",
                          })
                        : "2025-07-30",
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "vellum-ai",
                "X-Fern-SDK-Version": "1.12.2",
                "User-Agent": "vellum-ai/1.12.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.ComponentsSchemasComposioExecuteToolRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : undefined,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ComponentsSchemasComposioExecuteToolResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vellum.BadRequestError(_response.error.body, _response.rawResponse);
                case 403:
                    throw new Vellum.ForbiddenError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new Vellum.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.VellumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VellumError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VellumTimeoutError(
                    "Timeout exceeded when calling POST /integrations/v1/providers/{integration_provider}/integrations/{integration_name}/tools/{tool_name}/execute.",
                );
            case "unknown":
                throw new errors.VellumError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List all integrations
     *
     * @param {Vellum.IntegrationsListRequest} request
     * @param {Integrations.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.integrations.list()
     */
    public list(
        request: Vellum.IntegrationsListRequest = {},
        requestOptions?: Integrations.RequestOptions,
    ): core.HttpResponsePromise<Vellum.PaginatedSlimIntegrationReadList> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Vellum.IntegrationsListRequest = {},
        requestOptions?: Integrations.RequestOptions,
    ): Promise<core.WithRawResponse<Vellum.PaginatedSlimIntegrationReadList>> {
        const { integrationProvider, limit, offset, ordering, search, supportsIntegrationTriggers } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (integrationProvider !== undefined) {
            _queryParams["integration_provider"] = integrationProvider;
        }

        if (limit !== undefined) {
            _queryParams["limit"] = limit?.toString() ?? null;
        }

        if (offset !== undefined) {
            _queryParams["offset"] = offset?.toString() ?? null;
        }

        if (ordering !== undefined) {
            _queryParams["ordering"] = ordering;
        }

        if (search !== undefined) {
            _queryParams["search"] = search;
        }

        if (supportsIntegrationTriggers !== undefined) {
            _queryParams["supports_integration_triggers"] = supportsIntegrationTriggers;
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.VellumEnvironment.Production)
                        .default,
                "v1/integrations",
            ),
            method: "GET",
            headers: {
                "X-API-Version":
                    (await core.Supplier.get(this._options.apiVersion)) != null
                        ? serializers.ApiVersionEnum.jsonOrThrow(await core.Supplier.get(this._options.apiVersion), {
                              unrecognizedObjectKeys: "strip",
                          })
                        : "2025-07-30",
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "vellum-ai",
                "X-Fern-SDK-Version": "1.12.2",
                "User-Agent": "vellum-ai/1.12.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : undefined,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.PaginatedSlimIntegrationReadList.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VellumError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VellumError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VellumTimeoutError("Timeout exceeded when calling GET /v1/integrations.");
            case "unknown":
                throw new errors.VellumError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve an integration
     *
     * @param {string} id - A UUID string identifying this integration.
     * @param {Integrations.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.integrations.retrieve("id")
     */
    public retrieve(
        id: string,
        requestOptions?: Integrations.RequestOptions,
    ): core.HttpResponsePromise<Vellum.IntegrationRead> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(id, requestOptions));
    }

    private async __retrieve(
        id: string,
        requestOptions?: Integrations.RequestOptions,
    ): Promise<core.WithRawResponse<Vellum.IntegrationRead>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.VellumEnvironment.Production)
                        .default,
                `v1/integrations/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                "X-API-Version":
                    (await core.Supplier.get(this._options.apiVersion)) != null
                        ? serializers.ApiVersionEnum.jsonOrThrow(await core.Supplier.get(this._options.apiVersion), {
                              unrecognizedObjectKeys: "strip",
                          })
                        : "2025-07-30",
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "vellum-ai",
                "X-Fern-SDK-Version": "1.12.2",
                "User-Agent": "vellum-ai/1.12.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : undefined,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.IntegrationRead.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VellumError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VellumError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VellumTimeoutError("Timeout exceeded when calling GET /v1/integrations/{id}.");
            case "unknown":
                throw new errors.VellumError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-API-KEY": apiKeyValue };
    }
}
