/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../index";

export interface WorkflowPushRequest {
    /** The execution configuration of the workflow. */
    execConfig: Vellum.WorkflowPushExecConfig;
    workflowSandboxId?: string | null;
    deploymentConfig?: Vellum.WorkflowPushDeploymentConfigRequest | null;
    dryRun?: boolean;
    strict?: boolean;
}
