/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class VellumTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, VellumTimeoutError.prototype);
    }
}
