/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Vellum from "../../../../../api/index";
import * as core from "../../../../../core";

export const DeploySandboxWorkflowRequest: core.serialization.Schema<
    serializers.DeploySandboxWorkflowRequest.Raw,
    Vellum.DeploySandboxWorkflowRequest
> = core.serialization.object({
    workflowDeploymentId: core.serialization.property(
        "workflow_deployment_id",
        core.serialization.string().optionalNullable(),
    ),
    workflowDeploymentName: core.serialization.property(
        "workflow_deployment_name",
        core.serialization.string().optionalNullable(),
    ),
    label: core.serialization.string().optionalNullable(),
    releaseTags: core.serialization.property(
        "release_tags",
        core.serialization.list(core.serialization.string()).optionalNullable(),
    ),
    releaseDescription: core.serialization.property(
        "release_description",
        core.serialization.string().optionalNullable(),
    ),
});

export declare namespace DeploySandboxWorkflowRequest {
    export interface Raw {
        workflow_deployment_id?: (string | null) | null;
        workflow_deployment_name?: (string | null) | null;
        label?: (string | null) | null;
        release_tags?: (string[] | null) | null;
        release_description?: (string | null) | null;
    }
}
