/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface ApiRequestParentContext {
    parent?: Vellum.ParentContext | null;
    links?: Vellum.SpanLink[] | null;
    type: "API_REQUEST";
    spanId: string;
}
