/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "..";

export type ArrayVariableValueItem =
    | Vellum.ArrayVariableValueItem.String
    | Vellum.ArrayVariableValueItem.Number
    | Vellum.ArrayVariableValueItem.Json
    | Vellum.ArrayVariableValueItem.ChatHistory
    | Vellum.ArrayVariableValueItem.SearchResults
    | Vellum.ArrayVariableValueItem.Error_
    | Vellum.ArrayVariableValueItem.FunctionCall
    | Vellum.ArrayVariableValueItem.Image;

export declare namespace ArrayVariableValueItem {
    interface String extends Vellum.StringVariableValue {
        type: "STRING";
    }

    interface Number extends Vellum.NumberVariableValue {
        type: "NUMBER";
    }

    interface Json extends Vellum.JsonVariableValue {
        type: "JSON";
    }

    interface ChatHistory extends Vellum.ChatHistoryVariableValue {
        type: "CHAT_HISTORY";
    }

    interface SearchResults extends Vellum.SearchResultsVariableValue {
        type: "SEARCH_RESULTS";
    }

    interface Error_ extends Vellum.ErrorVariableValue {
        type: "ERROR";
    }

    interface FunctionCall extends Vellum.FunctionCallVariableValue {
        type: "FUNCTION_CALL";
    }

    interface Image extends Vellum.ImageVariableValue {
        type: "IMAGE";
    }
}
