/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * An audio value that is used in a chat message.
 */
export interface AudioChatMessageContent {
    type: "AUDIO";
    value: Vellum.VellumAudio;
}
