/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Basic vectorizer for sentence-transformers/multi-qa-mpnet-base-dot-v1.
 */
export interface BasicVectorizerSentenceTransformersMultiQaMpnetBaseDotV1Request {
    modelName: "sentence-transformers/multi-qa-mpnet-base-dot-v1";
    config?: Record<string, unknown>;
}
