/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChatMessageRole = "SYSTEM" | "ASSISTANT" | "USER";

export const ChatMessageRole = {
    System: "SYSTEM",
    Assistant: "ASSISTANT",
    User: "USER",
} as const;
