/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "..";

/**
 * The properties of a ChatMessagePromptTemplateBlock
 */
export interface ChatMessagePromptTemplateBlockPropertiesRequest {
    blocks: Vellum.PromptTemplateBlockRequest[];
    chatRole?: Vellum.ChatMessageRole;
    chatSource?: string;
    chatMessageUnterminated?: boolean;
}
