/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A Prompt Deployment's full details.
 */
export interface DeploymentRead {
    id: string;
    created: Date;
    /** A human-readable label for the deployment */
    label: string;
    /** A name that uniquely identifies this deployment within its workspace */
    name: string;
    /**
     * The current status of the deployment
     *
     * * `ACTIVE` - Active
     * * `ARCHIVED` - Archived
     * * `PENDING_DELETION` - Pending Deletion
     */
    status?: Vellum.EntityStatus;
    /** Deprecated. The value returned will always be 'PRODUCTION'. */
    environment?: Vellum.EnvironmentEnum | null;
    lastDeployedOn: Date;
    inputVariables: Vellum.VellumVariable[];
    /** A human-readable description of the deployment */
    description?: string | null;
    /** Deprecated. This now always returns an empty array. */
    activeModelVersionIds?: string[] | null;
    /** The ID of the history item associated with this Deployment's LATEST Release Tag */
    lastDeployedHistoryItemId: string;
}
