/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "..";

export interface DeploymentRead {
    id: string;
    created: string;
    /** A human-readable label for the deployment <span style="white-space: nowrap">`<= 150 characters`</span> */
    label: string;
    /** A name that uniquely identifies this deployment within its workspace <span style="white-space: nowrap">`<= 150 characters`</span> */
    name: string;
    /**
     * The current status of the deployment
     *
     * * `ACTIVE` - Active
     * * `INACTIVE` - Inactive
     * * `ARCHIVED` - Archived
     */
    status?: Vellum.DeploymentStatus;
    /**
     * The environment this deployment is used in
     *
     * * `DEVELOPMENT` - Development
     * * `STAGING` - Staging
     * * `PRODUCTION` - Production
     */
    environment?: Vellum.EnvironmentEnum;
    modelType: Vellum.ModelTypeDeprecated;
    activeModelVersionIds: string[];
    lastDeployedOn: string;
    inputVariables: Vellum.InputVariable[];
}
