/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Document {
    /** The ID of the document. */
    id: string;
    /** The human-readable name for the document. <span style="white-space: nowrap">`<= 1000 characters`</span> */
    label: string;
    /** The unique ID of the document as represented in an external system and specified when it was originally uploaded. */
    externalId?: string;
}
