/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface DocumentRead {
    id: string;
    /** The unique id of this document as it exists in the user's system. */
    externalId?: string | null;
    lastUploadedAt: Date;
    /** A human-readable label for the document. Defaults to the originally uploaded file's file name. */
    label: string;
    processingState: Vellum.DocumentProcessingState;
    /**
     * The current status of the document
     *
     * * `ACTIVE` - Active
     */
    status?: Vellum.DocumentStatus;
    originalFileUrl?: string | null;
    documentToDocumentIndexes: Vellum.DocumentDocumentToDocumentIndex[];
    /** A previously supplied JSON object containing metadata that can be filtered on when searching. */
    metadata?: Record<string, unknown> | null;
}
