/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface EnvironmentRead {
    id?: string;
    name: string;
    label: string;
    displayConfig?: Vellum.EnvironmentDisplayConfig | null;
}
