/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * * `EPHEMERAL` - EPHEMERAL
 */
export type EphemeralPromptCacheConfigTypeEnum = "EPHEMERAL";
export const EphemeralPromptCacheConfigTypeEnum = {
    Ephemeral: "EPHEMERAL",
} as const;
