/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EvaluationParams {
    /** The target value to compare the LLM output against. Typically what you expect or desire the LLM output to be. */
    target?: string;
}
