/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A value representing an array of Vellum variable values.
 */
export interface ExecutionArrayVellumValue {
    /** The variable's uniquely identifying internal id. */
    id: string;
    name: string;
    type: "ARRAY";
    value?: Vellum.ArrayVellumValueItem[];
}
