/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface ExecuteApiResponse {
    statusCode: number;
    text: string;
    json: Vellum.ExecuteApiResponseJson;
    headers: Record<string, string>;
}
