/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A slim representation of a Test Suite, as it exists within a Folder.
 */
export interface FolderEntityTestSuite {
    id: string;
    type: "TEST_SUITE";
    data: Vellum.FolderEntityTestSuiteData;
}
