/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface FolderEntityPromptSandboxData {
    id: string;
    label: string;
    created: Date;
    modified: Date;
    status: Vellum.EntityStatus;
    description?: string | null;
    lastDeployedOn?: Date | null;
}
