/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * The final data event returned indicating that the stream has ended and all final resolved values from the model can be found.
 */
export interface FulfilledAdHocExecutePromptEvent {
    outputs: Vellum.PromptOutput[];
    executionId: string;
    meta?: Vellum.AdHocFulfilledPromptExecutionMeta;
}
