/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The final resolved function call value.
 */
export interface FunctionCallChatMessageContentValueRequest {
    name: string;
    arguments: Record<string, unknown>;
    id?: string | null;
}
