/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * - `ANTHROPIC` - ANTHROPIC
 * - `AWS_BEDROCK` - AWS_BEDROCK
 * - `AZURE_OPENAI` - AZURE_OPENAI
 * - `COHERE` - COHERE
 * - `CUSTOM` - CUSTOM
 * - `FIREWORKS_AI` - FIREWORKS_AI
 * - `GOOGLE` - GOOGLE
 * - `GOOGLE_VERTEX_AI` - GOOGLE_VERTEX_AI
 * - `GROQ` - GROQ
 * - `HUGGINGFACE` - HUGGINGFACE
 * - `IBM_WATSONX` - IBM_WATSONX
 * - `MOSAICML` - MOSAICML
 * - `MYSTIC` - MYSTIC
 * - `OPENAI` - OPENAI
 * - `OPENPIPE` - OPENPIPE
 * - `PYQ` - PYQ
 * - `REPLICATE` - REPLICATE
 */
export type HostedByEnum =
    | "ANTHROPIC"
    | "AWS_BEDROCK"
    | "AZURE_OPENAI"
    | "COHERE"
    | "CUSTOM"
    | "FIREWORKS_AI"
    | "GOOGLE"
    | "GOOGLE_VERTEX_AI"
    | "GROQ"
    | "HUGGINGFACE"
    | "IBM_WATSONX"
    | "MOSAICML"
    | "MYSTIC"
    | "OPENAI"
    | "OPENPIPE"
    | "PYQ"
    | "REPLICATE";

export const HostedByEnum = {
    Anthropic: "ANTHROPIC",
    AwsBedrock: "AWS_BEDROCK",
    AzureOpenai: "AZURE_OPENAI",
    Cohere: "COHERE",
    Custom: "CUSTOM",
    FireworksAi: "FIREWORKS_AI",
    Google: "GOOGLE",
    GoogleVertexAi: "GOOGLE_VERTEX_AI",
    Groq: "GROQ",
    Huggingface: "HUGGINGFACE",
    IbmWatsonx: "IBM_WATSONX",
    Mosaicml: "MOSAICML",
    Mystic: "MYSTIC",
    Openai: "OPENAI",
    Openpipe: "OPENPIPE",
    Pyq: "PYQ",
    Replicate: "REPLICATE",
} as const;
