/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Tokenizer config for Hugging Face type tokenizers.
 */
export interface HuggingFaceTokenizerConfig {
    name: string;
    path?: string;
}
