/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A base Vellum primitive value representing an image.
 */
export interface ImageVellumValueRequest {
    value: Vellum.VellumImageRequest | null;
}
