/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * * `ENVIRONMENT` - ENVIRONMENT
 * * `USER` - USER
 */
export type IntegrationCredentialAccessType = "ENVIRONMENT" | "USER";
export const IntegrationCredentialAccessType = {
    Environment: "ENVIRONMENT",
    User: "USER",
} as const;
