/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface JsonInputRequest {
    /** The variable's name, as defined in the deployment. */
    name: string;
    value: Record<string, unknown>;
}
