/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A higher-order condition that combines one or more basic conditions or other higher-order conditions.
 */
export interface LogicalConditionGroupRequest {
    type: "LOGICAL_CONDITION_GROUP";
    conditions: Vellum.LogicalExpressionRequest[];
    combinator: Vellum.ConditionCombinator;
    negated: boolean;
}
