/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface MlModelDisplayConfigRequest {
    label: string;
    description: string;
    tags: Vellum.MlModelDisplayTag[];
    defaultDisplayPriority: number;
}
