/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MlModelUsage {
    outputTokenCount?: number;
    inputTokenCount?: number;
    inputCharCount?: number;
    outputCharCount?: number;
    computeNanos?: number;
    cacheCreationInputTokens?: number;
    cacheReadInputTokens?: number;
}
