/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { VellumApi } from "@fern-api/vellum";

export interface ModelVersionBuildConfig {
    /** The name of the base model used to create this model version, as identified by the LLM provider. */
    baseModel: string;
    sandboxSnapshot?: VellumApi.ModelVersionSandboxSnapshot;
}
