/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export type NamedScenarioInputRequest =
    | Vellum.NamedScenarioInputStringVariableValueRequest
    | Vellum.NamedScenarioInputJsonVariableValueRequest
    | Vellum.NamedScenarioInputChatHistoryVariableValueRequest
    | Vellum.NamedScenarioInputAudioVariableValueRequest
    | Vellum.NamedScenarioInputVideoVariableValueRequest
    | Vellum.NamedScenarioInputImageVariableValueRequest
    | Vellum.NamedScenarioInputDocumentVariableValueRequest;
