/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * Named Test Case value that is of type SEARCH_RESULTS
 */
export interface NamedTestCaseSearchResultsVariableValue {
    value: Vellum.SearchResult[] | null;
    name: string;
}
