/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * Named Test Case value that is of type ARRAY
 */
export interface NamedTestCaseArrayVariableValueRequest {
    type: "ARRAY";
    value?: Vellum.VellumValueRequest[];
    name: string;
}
