/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Named Test Case value that is of type JSON
 */
export interface NamedTestCaseJsonVariableValue {
    value?: Record<string, unknown>;
    name: string;
}
