/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * Named Test Case value that is of type ERROR
 */
export interface NamedTestCaseErrorVariableValue {
    type: "ERROR";
    value?: Vellum.VellumError;
    name: string;
}
