/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * An output returned by a node that is of type STRING.
 */
export interface NodeOutputCompiledStringValue {
    type: "STRING";
    value?: string | null;
    nodeOutputId: string;
    state?: Vellum.WorkflowNodeResultEventState;
}
