/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export type NodeOutputCompiledValue =
    | Vellum.NodeOutputCompiledStringValue
    | Vellum.NodeOutputCompiledNumberValue
    | Vellum.NodeOutputCompiledJsonValue
    | Vellum.NodeOutputCompiledChatHistoryValue
    | Vellum.NodeOutputCompiledSearchResultsValue
    | Vellum.NodeOutputCompiledErrorValue
    | Vellum.NodeOutputCompiledArrayValue
    | Vellum.NodeOutputCompiledFunctionCallValue
    | Vellum.NodeOutputCompiledThinkingValue;
