/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface NodeParentContext {
    parent?: Vellum.ParentContext | null;
    links?: Vellum.SpanLink[] | null;
    nodeDefinition: Vellum.VellumCodeResourceDefinition;
    type: "WORKFLOW_NODE";
    spanId: string;
}
