/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface NodeInputCompiledAudioValue {
    nodeInputId: string;
    key: string;
    type: "AUDIO";
    value?: Vellum.VellumAudio | null;
}
