/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * An output returned by a node that is of type ERROR.
 */
export interface NodeOutputCompiledErrorValue {
    type: "ERROR";
    value?: Vellum.VellumError | null;
    nodeOutputId: string;
    state?: Vellum.WorkflowNodeResultEventState;
}
