/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * An output returned by a node that is of type JSON.
 */
export interface NodeOutputCompiledJsonValue {
    type: "JSON";
    value?: unknown;
    nodeOutputId: string;
    state?: Vellum.WorkflowNodeResultEventState;
}
