/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A user input representing a number value
 */
export interface NumberInput {
    /** The variable's name */
    name: string;
    value: number;
}
