/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * An OpenAPI specification of a property with type 'enum'
 */
export interface OpenApiEnumProperty {
    type: "enum";
    title?: string;
    description?: string;
    enum: (Vellum.OpenApiEnumPropertyEnumItem | undefined)[];
    default?: Vellum.OpenApiEnumPropertyDefault;
}
