/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An OpenAPI specification of a parameter with type 'number'
 */
export interface OpenApiNumberPropertyRequest {
    minimum?: number;
    maximum?: number;
    format?: string;
    exclusiveMinimum?: boolean;
    exclusiveMaximum?: boolean;
    default?: number;
    title?: string;
    description?: string;
}
