/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Vellum } from "@fern-api/vellum";

export interface PaginatedSlimDocumentList {
    count?: number;
    next?: string;
    previous?: string;
    results?: Vellum.SlimDocument[];
}
