/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface PaginatedFolderEntityList {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Vellum.FolderEntity[];
}
