/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A block that holds a plain text string value.
 */
export interface PlainTextPromptBlock {
    blockType: "PLAIN_TEXT";
    state?: Vellum.PromptBlockState;
    cacheConfig?: Vellum.EphemeralPromptCacheConfig;
    text: string;
}
