/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface PromptDeploymentRelease {
    id: string;
    created: Date;
    environment: Vellum.ReleaseEnvironment;
    createdBy?: Vellum.ReleaseCreatedBy;
    promptVersion: Vellum.PromptDeploymentReleasePromptVersion;
    deployment: Vellum.PromptDeploymentReleasePromptDeployment;
    description?: string;
    releaseTags: Vellum.ReleaseReleaseTag[];
    reviews: Vellum.SlimReleaseReview[];
}
