/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PromptTemplateInputVariableRequest {
    /** The name of the input variable. <span style="white-space: nowrap">`non-empty`</span> */
    key: string;
}
