/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export type PromptRequestInputRequest =
    | Vellum.PromptRequestStringInputRequest
    | Vellum.PromptRequestJsonInputRequest
    | Vellum.PromptRequestChatHistoryInputRequest;
