/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface PromptNodeResultData {
    executionMeta?: Vellum.PromptNodeExecutionMeta | null;
    outputId: string;
    arrayOutputId?: string | null;
    executionId?: string | null;
    text?: string | null;
    delta?: string | null;
}
