/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "..";

export interface RegisteredPromptInputVariableRequest {
    /** <span style="white-space: nowrap">`non-empty`</span> */
    key: string;
    /** <span style="white-space: nowrap">`non-empty`</span> */
    id?: string;
    type?: Vellum.VellumVariableType;
}
