/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "..";

export interface SandboxScenario {
    label?: string;
    /** The inputs for the scenario */
    inputs: Vellum.SandboxInput[];
    metricInputParams?: Vellum.SandboxMetricInputParams;
    /** The id of the scenario */
    id: string;
}
