/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export type ScenarioInput =
    | Vellum.ScenarioInputStringVariableValue
    | Vellum.ScenarioInputJsonVariableValue
    | Vellum.ScenarioInputChatHistoryVariableValue
    | Vellum.ScenarioInputAudioVariableValue
    | Vellum.ScenarioInputVideoVariableValue
    | Vellum.ScenarioInputImageVariableValue
    | Vellum.ScenarioInputDocumentVariableValue;
