/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface SearchNodeResultData {
    resultsOutputId: string;
    /** The results of the search. Each result represents a chunk that matches the search query. */
    results: Vellum.SearchResult[];
    textOutputId: string;
    text?: string | null;
}
