/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SearchNodeResultData {
    resultsOutputId: string;
    results: Record<string, unknown>[];
    textOutputId?: string;
    text?: string;
}
