/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "..";

export interface SearchResponse {
    /** The results of the search. Each result represents a chunk that matches the search query. */
    results: Vellum.SearchResult[];
}
