/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * * `DEBUG` - DEBUG
 * * `INFO` - INFO
 * * `WARNING` - WARNING
 * * `ERROR` - ERROR
 */
export type SeverityEnum = "DEBUG" | "INFO" | "WARNING" | "ERROR";
export const SeverityEnum = {
    Debug: "DEBUG",
    Info: "INFO",
    Warning: "WARNING",
    Error: "ERROR",
} as const;
