/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface SlimIntegrationRead {
    id: string;
    label?: string;
    iconUrl: string;
    name: Vellum.IntegrationName;
    provider: Vellum.IntegrationProvider;
}
