/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export type SlimToolDefinition = Vellum.SlimToolDefinition.Composio;

export namespace SlimToolDefinition {
    export interface Composio extends Vellum.SlimComposioToolDefinition {
        provider: "COMPOSIO";
    }
}
