/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface SlimWorkflowDeployment {
    id: string;
    /** A name that uniquely identifies this workflow deployment within its workspace */
    name: string;
    /** A human-readable label for the workflow deployment */
    label: string;
    /**
     * The current status of the workflow deployment
     *
     * * `ACTIVE` - Active
     * * `ARCHIVED` - Archived
     */
    status?: Vellum.EntityStatus;
    /**
     * The environment this workflow deployment is used in
     *
     * * `DEVELOPMENT` - Development
     * * `STAGING` - Staging
     * * `PRODUCTION` - Production
     */
    environment?: Vellum.EnvironmentEnum | null;
    created: Date;
    lastDeployedOn: Date;
    /** The input variables this Workflow Deployment expects to receive values for when it is executed. */
    inputVariables: Vellum.VellumVariable[];
    /** The output variables this Workflow Deployment will produce when it is executed. */
    outputVariables: Vellum.VellumVariable[];
    /** A human-readable description of the workflow deployment */
    description?: string | null;
}
