/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A value representing a string.
 */
export interface StringVellumValueRequest {
    type: Vellum.StringEnum;
    value: string | null;
}
