/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface TemplatingNodeFunctionCallResult {
    id: string;
    type: "FUNCTION_CALL";
    value?: Vellum.FunctionCall;
}
