/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A chat history value for a variable in a Test Case.
 */
export interface TestCaseChatHistoryVariableValue {
    variableId: string;
    name: string;
    value: Vellum.ChatMessage[] | null;
}
