/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * An image value for a variable in a Test Case.
 */
export interface TestCaseImageVariableValue {
    variableId: string;
    name?: string;
    type: "IMAGE";
    value: Vellum.VellumImage;
}
