/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "..";

export interface TestSuiteTestCase {
    id?: string;
    label?: string;
    inputValues: Vellum.TestCaseVariableValue[];
    evaluationValues: Vellum.TestCaseVariableValue[];
}
