/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * - `DEPLOYMENT_RELEASE_TAG` - DEPLOYMENT_RELEASE_TAG
 */
export type TestSuiteRunDeploymentReleaseTagExecConfigTypeEnum = "DEPLOYMENT_RELEASE_TAG";
