/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A document value for a variable in a Test Case.
 */
export interface TestCaseDocumentVariableValue {
    variableId: string;
    name?: string;
    type: "DOCUMENT";
    value: Vellum.VellumDocument;
}
