/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export type VellumValueRequest =
    | Vellum.StringVellumValueRequest
    | Vellum.NumberVellumValueRequest
    | Vellum.JsonVellumValueRequest
    | Vellum.AudioVellumValueRequest
    | Vellum.VideoVellumValueRequest
    | Vellum.ImageVellumValueRequest
    | Vellum.DocumentVellumValueRequest
    | Vellum.FunctionCallVellumValueRequest
    | Vellum.ErrorVellumValueRequest
    | Vellum.ArrayVellumValueRequest
    | Vellum.ChatHistoryVellumValueRequest
    | Vellum.SearchResultsVellumValueRequest
    | Vellum.ThinkingVellumValueRequest;
