/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A base Vellum primitive value representing a video.
 */
export interface VideoVellumValueRequest {
    type: "VIDEO";
    value?: Vellum.VellumVideoRequest | null;
}
