/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export type WorkflowNodeResultData =
    | Vellum.PromptNodeResult
    | Vellum.SearchNodeResult
    | Vellum.TemplatingNodeResult
    | Vellum.CodeExecutionNodeResult
    | Vellum.ConditionalNodeResult
    | Vellum.ApiNodeResult
    | Vellum.TerminalNodeResult
    | Vellum.MergeNodeResult
    | Vellum.SubworkflowNodeResult
    | Vellum.MetricNodeResult
    | Vellum.MapNodeResult;
