/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A video output from a Workflow execution.
 */
export interface WorkflowOutputVideo {
    id: string;
    /** The output's name, as defined in the workflow */
    name: string;
    type: "VIDEO";
    value?: Vellum.VellumVideo | null;
}
