/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * The input for an audio variable in a Workflow.
 */
export interface WorkflowRequestAudioInputRequest {
    /** The variable's name, as defined in the Workflow. */
    name: string;
    type: "AUDIO";
    value: Vellum.VellumAudioRequest;
}
