/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A number output streamed from a Workflow execution.
 */
export interface WorkflowResultEventOutputDataNumber {
    id?: string | null;
    name: string;
    state: Vellum.WorkflowNodeResultEventState;
    nodeId?: string | null;
    /** The newly output string value. Only relevant for string outputs with a state of STREAMING. */
    delta?: string | null;
    value: number | null;
}
