/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "..";

export interface WorkflowResultEventOutputDataJson {
    name: string;
    state: Vellum.WorkflowNodeResultEventState;
    nodeId: string;
    value?: Record<string, unknown>;
}
