/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A WORKFLOW-level event emitted from the workflow's execution.
 */
export interface WorkflowExecutionWorkflowResultEvent {
    executionId: string;
    runId?: string | null;
    externalId?: string | null;
    type: "WORKFLOW";
    data: Vellum.WorkflowResultEvent;
}
