/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * A Workflow Deployment's full details.
 */
export interface WorkflowDeploymentRead {
    id: string;
    /** A name that uniquely identifies this workflow deployment within its workspace */
    name: string;
    /** A human-readable label for the workflow deployment */
    label: string;
    /**
     * The current status of the workflow deployment
     *
     * * `ACTIVE` - Active
     * * `ARCHIVED` - Archived
     */
    status?: Vellum.EntityStatus;
    /** Deprecated. The value returned will always be 'PRODUCTION'. */
    environment?: Vellum.EnvironmentEnum | null;
    created: Date;
    lastDeployedOn: Date;
    /** The ID of the history item associated with this Workflow Deployment's LATEST Release Tag */
    lastDeployedHistoryItemId: string;
    /** The input variables this Workflow Deployment expects to receive values for when it is executed. */
    inputVariables: Vellum.VellumVariable[];
    /** The output variables this Workflow Deployment produces values for when it's executed. */
    outputVariables: Vellum.VellumVariable[];
    /** A human-readable description of the workflow deployment */
    description?: string | null;
    /** Information used to display this Workflow Deployment. */
    displayData?: Vellum.WorkflowDeploymentDisplayData | null;
}
