/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorkflowPushDeploymentConfigRequest {
    label?: string;
    name?: string;
    description?: string;
    releaseTags?: string[];
}
