/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface WorkflowDeploymentReleaseWorkflowVersion {
    id?: string;
    inputVariables?: Vellum.VellumVariable[];
    outputVariables?: Vellum.VellumVariable[];
}
