/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

/**
 * The input for a document variable in a Workflow.
 */
export interface WorkflowRequestDocumentInputRequest {
    /** The variable's name, as defined in the Workflow. */
    name: string;
    type: "DOCUMENT";
    value: Vellum.VellumDocumentRequest;
}
