/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WorkflowReleaseTagEnum = "WORKFLOW_RELEASE_TAG";
export const WorkflowReleaseTagEnum = {
    WorkflowReleaseTag: "WORKFLOW_RELEASE_TAG",
} as const;
