/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../index";

export interface WorkflowEventExecutionRead {
    spanId: string;
    parentContext?: Vellum.WorkflowDeploymentParentContext;
    start: Date;
    end?: Date;
    inputs: Vellum.ExecutionVellumValue[];
    outputs: Vellum.ExecutionVellumValue[];
    error?: Vellum.WorkflowError;
    latestActual?: Vellum.WorkflowExecutionActual;
    metricResults: Vellum.WorkflowExecutionViewOnlineEvalMetricResult[];
    usageResults: Vellum.WorkflowExecutionUsageCalculationFulfilledBody[];
    spans: Vellum.VellumSpan[];
}
