/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DocumentIndexesListRequestStatus = "ACTIVE" | "ARCHIVED" | "PENDING_DELETION";
export const DocumentIndexesListRequestStatus = {
    Active: "ACTIVE",
    Archived: "ARCHIVED",
    PendingDeletion: "PENDING_DELETION",
} as const;
