/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../index";

/**
 * @example
 *     {
 *         code: "code",
 *         runtime: "PYTHON_3_11_6",
 *         inputValues: [{
 *                 name: "name",
 *                 type: "STRING",
 *                 value: "value"
 *             }],
 *         packages: [{
 *                 version: "version",
 *                 name: "name"
 *             }],
 *         outputType: "STRING"
 *     }
 */
export interface CodeExecutorRequest {
    code: string;
    runtime: Vellum.CodeExecutionRuntime;
    inputValues: Vellum.CodeExecutorInputRequest[];
    packages: Vellum.CodeExecutionPackageRequest[];
    outputType: Vellum.VellumVariableType;
}
