/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../..";

/**
 * @example
 *     {
 *         actuals: [{}]
 *     }
 */
export interface SubmitCompletionActualsRequest {
    /** The ID of the deployment. Must provide either this or deployment_name. */
    deploymentId?: string;
    /** The name of the deployment. Must provide either this or deployment_id. */
    deploymentName?: string;
    /** Feedback regarding the quality of previously generated completions */
    actuals: Vellum.SubmitCompletionActualRequest[];
}
