/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { StringVariableValue } from "./StringVariableValue";
import { NumberVariableValue } from "./NumberVariableValue";
import { JsonVariableValue } from "./JsonVariableValue";
import { ErrorVariableValue } from "./ErrorVariableValue";
import { FunctionCallVariableValue } from "./FunctionCallVariableValue";
import { ImageVariableValue } from "./ImageVariableValue";

export const ArrayVariableValueItem: core.serialization.Schema<
    serializers.ArrayVariableValueItem.Raw,
    Vellum.ArrayVariableValueItem
> = core.serialization.undiscriminatedUnion([
    StringVariableValue,
    NumberVariableValue,
    JsonVariableValue,
    ErrorVariableValue,
    FunctionCallVariableValue,
    ImageVariableValue,
]);

export declare namespace ArrayVariableValueItem {
    type Raw =
        | StringVariableValue.Raw
        | NumberVariableValue.Raw
        | JsonVariableValue.Raw
        | ErrorVariableValue.Raw
        | FunctionCallVariableValue.Raw
        | ImageVariableValue.Raw;
}
