/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumAudioRequest } from "./VellumAudioRequest";

export const AudioVellumValueRequest: core.serialization.ObjectSchema<
    serializers.AudioVellumValueRequest.Raw,
    Vellum.AudioVellumValueRequest
> = core.serialization.object({
    value: VellumAudioRequest.nullable(),
});

export declare namespace AudioVellumValueRequest {
    export interface Raw {
        value: VellumAudioRequest.Raw | null;
    }
}
