/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const BasicVectorizerSentenceTransformersMultiQaMpnetBaseDotV1Request: core.serialization.ObjectSchema<
    serializers.BasicVectorizerSentenceTransformersMultiQaMpnetBaseDotV1Request.Raw,
    Vellum.BasicVectorizerSentenceTransformersMultiQaMpnetBaseDotV1Request
> = core.serialization.object({
    config: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace BasicVectorizerSentenceTransformersMultiQaMpnetBaseDotV1Request {
    interface Raw {
        config?: Record<string, unknown> | null;
    }
}
