/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";
import { PromptTemplateBlockState } from "./PromptTemplateBlockState";

export const ChatHistoryPromptTemplateBlockRequest: core.serialization.ObjectSchema<
    serializers.ChatHistoryPromptTemplateBlockRequest.Raw,
    Vellum.ChatHistoryPromptTemplateBlockRequest
> = core.serialization.object({
    properties: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    id: core.serialization.string(),
    state: PromptTemplateBlockState.optional(),
});

export declare namespace ChatHistoryPromptTemplateBlockRequest {
    interface Raw {
        properties: Record<string, unknown>;
        id: string;
        state?: PromptTemplateBlockState.Raw | null;
    }
}
