/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ChatMessageRole } from "./ChatMessageRole";
import { ChatMessageContentRequest } from "./ChatMessageContentRequest";

export const ChatMessageRequest: core.serialization.ObjectSchema<
    serializers.ChatMessageRequest.Raw,
    Vellum.ChatMessageRequest
> = core.serialization.object({
    text: core.serialization.string().optionalNullable(),
    role: ChatMessageRole,
    content: ChatMessageContentRequest.optionalNullable(),
    source: core.serialization.string().optionalNullable(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
});

export declare namespace ChatMessageRequest {
    export interface Raw {
        text?: (string | null) | null;
        role: ChatMessageRole.Raw;
        content?: (ChatMessageContentRequest.Raw | null) | null;
        source?: (string | null) | null;
        metadata?: (Record<string, unknown> | null) | null;
    }
}
