/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const ChatMessageRole: core.serialization.Schema<serializers.ChatMessageRole.Raw, Vellum.ChatMessageRole> =
    core.serialization.enum_(["SYSTEM", "ASSISTANT", "USER", "FUNCTION"]);

export declare namespace ChatMessageRole {
    export type Raw = "SYSTEM" | "ASSISTANT" | "USER" | "FUNCTION";
}
