/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ChatMessage } from "./ChatMessage";

export const ChatHistoryVellumValue: core.serialization.ObjectSchema<
    serializers.ChatHistoryVellumValue.Raw,
    Vellum.ChatHistoryVellumValue
> = core.serialization.object({
    value: core.serialization.list(ChatMessage).nullable(),
});

export declare namespace ChatHistoryVellumValue {
    export interface Raw {
        value: ChatMessage.Raw[] | null;
    }
}
