/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";
import { ChatMessageRole } from "./ChatMessageRole";
import { ChatMessageContentRequest } from "./ChatMessageContentRequest";

export const ChatMessageRequest: core.serialization.ObjectSchema<
    serializers.ChatMessageRequest.Raw,
    Vellum.ChatMessageRequest
> = core.serialization.object({
    text: core.serialization.string().optional(),
    role: ChatMessageRole,
    content: ChatMessageContentRequest.optional(),
    source: core.serialization.string().optional(),
});

export declare namespace ChatMessageRequest {
    interface Raw {
        text?: string | null;
        role: ChatMessageRole.Raw;
        content?: ChatMessageContentRequest.Raw | null;
        source?: string | null;
    }
}
