/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const ChatMessageRole: core.serialization.Schema<serializers.ChatMessageRole.Raw, Vellum.ChatMessageRole> =
    core.serialization.enum_(["SYSTEM", "ASSISTANT", "USER"]);

export declare namespace ChatMessageRole {
    type Raw = "SYSTEM" | "ASSISTANT" | "USER";
}
