/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const CodeExecutionNodeStringResult: core.serialization.ObjectSchema<
    serializers.CodeExecutionNodeStringResult.Raw,
    Vellum.CodeExecutionNodeStringResult
> = core.serialization.object({
    id: core.serialization.string(),
    value: core.serialization.string().nullable(),
});

export declare namespace CodeExecutionNodeStringResult {
    export interface Raw {
        id: string;
        value: string | null;
    }
}
