/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const CodeExecutionNodeStringResult: core.serialization.ObjectSchema<
    serializers.CodeExecutionNodeStringResult.Raw,
    Vellum.CodeExecutionNodeStringResult
> = core.serialization.object({
    id: core.serialization.string(),
    type: core.serialization.stringLiteral("STRING"),
    value: core.serialization.string().optional(),
});

export declare namespace CodeExecutionNodeStringResult {
    interface Raw {
        id: string;
        type: "STRING";
        value?: string | null;
    }
}
