/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ComposioToolDefinition } from "./ComposioToolDefinition";

export const ComponentsSchemasComposioToolDefinition: core.serialization.ObjectSchema<
    serializers.ComponentsSchemasComposioToolDefinition.Raw,
    Vellum.ComponentsSchemasComposioToolDefinition
> = ComposioToolDefinition;

export declare namespace ComponentsSchemasComposioToolDefinition {
    export type Raw = ComposioToolDefinition.Raw;
}
