/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { SlimComposioToolDefinition } from "./SlimComposioToolDefinition";

export const ComponentsSchemasSlimComposioToolDefinition: core.serialization.ObjectSchema<
    serializers.ComponentsSchemasSlimComposioToolDefinition.Raw,
    Vellum.ComponentsSchemasSlimComposioToolDefinition
> = SlimComposioToolDefinition;

export declare namespace ComponentsSchemasSlimComposioToolDefinition {
    export type Raw = SlimComposioToolDefinition.Raw;
}
