/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const ContainerImageContainerImageTag: core.serialization.ObjectSchema<
    serializers.ContainerImageContainerImageTag.Raw,
    Vellum.ContainerImageContainerImageTag
> = core.serialization.object({
    name: core.serialization.string(),
    modified: core.serialization.date(),
    historyItemSha: core.serialization.property("history_item_sha", core.serialization.string().optional()),
});

export declare namespace ContainerImageContainerImageTag {
    export interface Raw {
        name: string;
        modified: string;
        history_item_sha?: string | null;
    }
}
