/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { DelimiterChunkerConfigRequest } from "./DelimiterChunkerConfigRequest";

export const DelimiterChunkingRequest: core.serialization.ObjectSchema<
    serializers.DelimiterChunkingRequest.Raw,
    Vellum.DelimiterChunkingRequest
> = core.serialization.object({
    chunkerName: core.serialization.property("chunker_name", core.serialization.stringLiteral("delimiter-chunker")),
    chunkerConfig: core.serialization.property("chunker_config", DelimiterChunkerConfigRequest.optional()),
});

export declare namespace DelimiterChunkingRequest {
    export interface Raw {
        chunker_name: "delimiter-chunker";
        chunker_config?: DelimiterChunkerConfigRequest.Raw | null;
    }
}
