/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { DelimiterChunkerConfig } from "./DelimiterChunkerConfig";

export const DelimiterChunking: core.serialization.ObjectSchema<
    serializers.DelimiterChunking.Raw,
    Vellum.DelimiterChunking
> = core.serialization.object({
    chunkerConfig: core.serialization.property("chunker_config", DelimiterChunkerConfig.optional()),
});

export declare namespace DelimiterChunking {
    export interface Raw {
        chunker_config?: DelimiterChunkerConfig.Raw | null;
    }
}
