/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const DeploymentProviderPayloadResponse: core.serialization.ObjectSchema<
    serializers.DeploymentProviderPayloadResponse.Raw,
    Vellum.DeploymentProviderPayloadResponse
> = core.serialization.object({
    payload: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace DeploymentProviderPayloadResponse {
    interface Raw {
        payload: Record<string, unknown>;
    }
}
