/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const DockerServiceToken: core.serialization.ObjectSchema<
    serializers.DockerServiceToken.Raw,
    Vellum.DockerServiceToken
> = core.serialization.object({
    accessToken: core.serialization.property("access_token", core.serialization.string()),
    organizationId: core.serialization.property("organization_id", core.serialization.string()),
    repository: core.serialization.string(),
});

export declare namespace DockerServiceToken {
    export interface Raw {
        access_token: string;
        organization_id: string;
        repository: string;
    }
}
