/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const DocumentIndexStatus: core.serialization.Schema<
    serializers.DocumentIndexStatus.Raw,
    Vellum.DocumentIndexStatus
> = core.serialization.enum_(["ACTIVE", "ARCHIVED"]);

export declare namespace DocumentIndexStatus {
    type Raw = "ACTIVE" | "ARCHIVED";
}
