/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { EntityStatus } from "./EntityStatus";
import { DocumentIndexIndexingConfig } from "./DocumentIndexIndexingConfig";

export const DocumentIndexRead: core.serialization.ObjectSchema<
    serializers.DocumentIndexRead.Raw,
    Vellum.DocumentIndexRead
> = core.serialization.object({
    id: core.serialization.string(),
    created: core.serialization.date(),
    label: core.serialization.string(),
    name: core.serialization.string(),
    status: EntityStatus.optional(),
    indexingConfig: core.serialization.property("indexing_config", DocumentIndexIndexingConfig),
});

export declare namespace DocumentIndexRead {
    export interface Raw {
        id: string;
        created: string;
        label: string;
        name: string;
        status?: EntityStatus.Raw | null;
        indexing_config: DocumentIndexIndexingConfig.Raw;
    }
}
