/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const EntityVisibility: core.serialization.Schema<serializers.EntityVisibility.Raw, Vellum.EntityVisibility> =
    core.serialization.enum_(["DEFAULT", "PUBLIC", "PRIVATE", "DISABLED"]);

export declare namespace EntityVisibility {
    export type Raw = "DEFAULT" | "PUBLIC" | "PRIVATE" | "DISABLED";
}
