/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const EntityStatus: core.serialization.Schema<serializers.EntityStatus.Raw, Vellum.EntityStatus> =
    core.serialization.enum_(["ACTIVE", "ARCHIVED"]);

export declare namespace EntityStatus {
    type Raw = "ACTIVE" | "ARCHIVED";
}
