/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { EnvironmentDisplayConfig } from "./EnvironmentDisplayConfig";

export const EnvironmentRead: core.serialization.ObjectSchema<serializers.EnvironmentRead.Raw, Vellum.EnvironmentRead> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        name: core.serialization.string(),
        label: core.serialization.string(),
        displayConfig: core.serialization.property("display_config", EnvironmentDisplayConfig.optionalNullable()),
    });

export declare namespace EnvironmentRead {
    export interface Raw {
        id?: string | null;
        name: string;
        label: string;
        display_config?: (EnvironmentDisplayConfig.Raw | null) | null;
    }
}
