/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumErrorRequest } from "./VellumErrorRequest";

export const ErrorInputRequest: core.serialization.ObjectSchema<
    serializers.ErrorInputRequest.Raw,
    Vellum.ErrorInputRequest
> = core.serialization.object({
    name: core.serialization.string(),
    type: core.serialization.stringLiteral("ERROR"),
    value: VellumErrorRequest,
});

export declare namespace ErrorInputRequest {
    interface Raw {
        name: string;
        type: "ERROR";
        value: VellumErrorRequest.Raw;
    }
}
