/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const EventCreateResponse: core.serialization.ObjectSchema<
    serializers.EventCreateResponse.Raw,
    Vellum.EventCreateResponse
> = core.serialization.object({
    success: core.serialization.boolean().optional(),
});

export declare namespace EventCreateResponse {
    export interface Raw {
        success?: boolean | null;
    }
}
