/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const ExecutionStringVellumValue: core.serialization.ObjectSchema<
    serializers.ExecutionStringVellumValue.Raw,
    Vellum.ExecutionStringVellumValue
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    type: core.serialization.stringLiteral("STRING"),
    value: core.serialization.string().optional(),
});

export declare namespace ExecutionStringVellumValue {
    export interface Raw {
        id: string;
        name: string;
        type: "STRING";
        value?: string | null;
    }
}
