/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ExecuteApiResponseJson } from "./ExecuteApiResponseJson";

export const ExecuteApiResponse: core.serialization.ObjectSchema<
    serializers.ExecuteApiResponse.Raw,
    Vellum.ExecuteApiResponse
> = core.serialization.object({
    statusCode: core.serialization.property("status_code", core.serialization.number()),
    text: core.serialization.string(),
    json: ExecuteApiResponseJson.optionalNullable(),
    headers: core.serialization.record(core.serialization.string(), core.serialization.string()),
});

export declare namespace ExecuteApiResponse {
    export interface Raw {
        status_code: number;
        text: string;
        json?: (ExecuteApiResponseJson.Raw | null) | null;
        headers: Record<string, string>;
    }
}
