/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { EntityStatus } from "./EntityStatus";

export const FolderEntityPromptSandboxData: core.serialization.ObjectSchema<
    serializers.FolderEntityPromptSandboxData.Raw,
    Vellum.FolderEntityPromptSandboxData
> = core.serialization.object({
    id: core.serialization.string(),
    label: core.serialization.string(),
    created: core.serialization.date(),
    modified: core.serialization.date(),
    status: EntityStatus,
    description: core.serialization.string().optionalNullable(),
    lastDeployedOn: core.serialization.property("last_deployed_on", core.serialization.date().optionalNullable()),
});

export declare namespace FolderEntityPromptSandboxData {
    export interface Raw {
        id: string;
        label: string;
        created: string;
        modified: string;
        status: EntityStatus.Raw;
        description?: (string | null) | null;
        last_deployed_on?: (string | null) | null;
    }
}
