/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";
import { PromptOutput } from "./PromptOutput";
import { FulfilledPromptExecutionMeta } from "./FulfilledPromptExecutionMeta";

export const FulfilledExecutePromptEvent: core.serialization.ObjectSchema<
    serializers.FulfilledExecutePromptEvent.Raw,
    Vellum.FulfilledExecutePromptEvent
> = core.serialization.object({
    outputs: core.serialization.list(PromptOutput),
    executionId: core.serialization.property("execution_id", core.serialization.string()),
    meta: FulfilledPromptExecutionMeta.optional(),
});

export declare namespace FulfilledExecutePromptEvent {
    interface Raw {
        outputs: PromptOutput.Raw[];
        execution_id: string;
        meta?: FulfilledPromptExecutionMeta.Raw | null;
    }
}
