/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { FinishReasonEnum } from "./FinishReasonEnum";
import { MlModelUsage } from "./MlModelUsage";
import { Price } from "./Price";

export const FulfilledPromptExecutionMeta: core.serialization.ObjectSchema<
    serializers.FulfilledPromptExecutionMeta.Raw,
    Vellum.FulfilledPromptExecutionMeta
> = core.serialization.object({
    latency: core.serialization.number().optionalNullable(),
    finishReason: core.serialization.property("finish_reason", FinishReasonEnum.optionalNullable()),
    usage: MlModelUsage.optionalNullable(),
    cost: Price.optionalNullable(),
});

export declare namespace FulfilledPromptExecutionMeta {
    export interface Raw {
        latency?: (number | null) | null;
        finish_reason?: (FinishReasonEnum.Raw | null) | null;
        usage?: (MlModelUsage.Raw | null) | null;
        cost?: (Price.Raw | null) | null;
    }
}
