/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { PromptExecutionMeta } from "./PromptExecutionMeta";
import { PromptOutput } from "./PromptOutput";

export const FulfilledExecutePromptResponse: core.serialization.ObjectSchema<
    serializers.FulfilledExecutePromptResponse.Raw,
    Vellum.FulfilledExecutePromptResponse
> = core.serialization.object({
    meta: PromptExecutionMeta.optional(),
    raw: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    executionId: core.serialization.property("execution_id", core.serialization.string()),
    state: core.serialization.stringLiteral("FULFILLED"),
    outputs: core.serialization.list(PromptOutput),
    chatMessageMetadata: core.serialization.property(
        "chat_message_metadata",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    ),
});

export declare namespace FulfilledExecutePromptResponse {
    export interface Raw {
        meta?: PromptExecutionMeta.Raw | null;
        raw?: Record<string, unknown> | null;
        execution_id: string;
        state: "FULFILLED";
        outputs: PromptOutput.Raw[];
        chat_message_metadata?: (Record<string, unknown> | null) | null;
    }
}
