/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { FunctionCall } from "./FunctionCall";

export const FunctionCallVellumValue: core.serialization.ObjectSchema<
    serializers.FunctionCallVellumValue.Raw,
    Vellum.FunctionCallVellumValue
> = core.serialization.object({
    value: FunctionCall.nullable(),
});

export declare namespace FunctionCallVellumValue {
    export interface Raw {
        value: FunctionCall.Raw | null;
    }
}
