/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { LogprobsEnum } from "./LogprobsEnum";

export const GenerateOptionsRequest: core.serialization.ObjectSchema<
    serializers.GenerateOptionsRequest.Raw,
    Vellum.GenerateOptionsRequest
> = core.serialization.object({
    logprobs: LogprobsEnum.optional(),
});

export declare namespace GenerateOptionsRequest {
    interface Raw {
        logprobs?: LogprobsEnum.Raw | null;
    }
}
