/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const GenerateErrorResponse: core.serialization.ObjectSchema<
    serializers.GenerateErrorResponse.Raw,
    Vellum.GenerateErrorResponse
> = core.serialization.object({
    detail: core.serialization.string(),
});

export declare namespace GenerateErrorResponse {
    interface Raw {
        detail: string;
    }
}
