/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const GenerateResult: core.serialization.ObjectSchema<serializers.GenerateResult.Raw, Vellum.GenerateResult> =
    core.serialization.object({
        data: core.serialization.lazyObject(async () => (await import("..")).GenerateResultData).optional(),
        error: core.serialization.lazyObject(async () => (await import("..")).GenerateResultError).optional(),
    });

export declare namespace GenerateResult {
    interface Raw {
        data?: serializers.GenerateResultData.Raw | null;
        error?: serializers.GenerateResultError.Raw | null;
    }
}
