/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { OpenAiVectorizerTextEmbedding3SmallRequest } from "./OpenAiVectorizerTextEmbedding3SmallRequest";
import { OpenAiVectorizerTextEmbedding3LargeRequest } from "./OpenAiVectorizerTextEmbedding3LargeRequest";
import { OpenAiVectorizerTextEmbeddingAda002Request } from "./OpenAiVectorizerTextEmbeddingAda002Request";
import { BasicVectorizerIntfloatMultilingualE5LargeRequest } from "./BasicVectorizerIntfloatMultilingualE5LargeRequest";
import { BasicVectorizerSentenceTransformersMultiQaMpnetBaseCosV1Request } from "./BasicVectorizerSentenceTransformersMultiQaMpnetBaseCosV1Request";
import { BasicVectorizerSentenceTransformersMultiQaMpnetBaseDotV1Request } from "./BasicVectorizerSentenceTransformersMultiQaMpnetBaseDotV1Request";
import { HkunlpInstructorXlVectorizerRequest } from "./HkunlpInstructorXlVectorizerRequest";
import { GoogleVertexAiVectorizerTextEmbedding004Request } from "./GoogleVertexAiVectorizerTextEmbedding004Request";
import { GoogleVertexAiVectorizerTextMultilingualEmbedding002Request } from "./GoogleVertexAiVectorizerTextMultilingualEmbedding002Request";
import { GoogleVertexAiVectorizerGeminiEmbedding001Request } from "./GoogleVertexAiVectorizerGeminiEmbedding001Request";
import { FastEmbedVectorizerBaaiBgeSmallEnV15Request } from "./FastEmbedVectorizerBaaiBgeSmallEnV15Request";
import { PrivateVectorizerRequest } from "./PrivateVectorizerRequest";

export const IndexingConfigVectorizerRequest: core.serialization.Schema<
    serializers.IndexingConfigVectorizerRequest.Raw,
    Vellum.IndexingConfigVectorizerRequest
> = core.serialization.undiscriminatedUnion([
    OpenAiVectorizerTextEmbedding3SmallRequest,
    OpenAiVectorizerTextEmbedding3LargeRequest,
    OpenAiVectorizerTextEmbeddingAda002Request,
    BasicVectorizerIntfloatMultilingualE5LargeRequest,
    BasicVectorizerSentenceTransformersMultiQaMpnetBaseCosV1Request,
    BasicVectorizerSentenceTransformersMultiQaMpnetBaseDotV1Request,
    HkunlpInstructorXlVectorizerRequest,
    GoogleVertexAiVectorizerTextEmbedding004Request,
    GoogleVertexAiVectorizerTextMultilingualEmbedding002Request,
    GoogleVertexAiVectorizerGeminiEmbedding001Request,
    FastEmbedVectorizerBaaiBgeSmallEnV15Request,
    PrivateVectorizerRequest,
]);

export declare namespace IndexingConfigVectorizerRequest {
    export type Raw =
        | OpenAiVectorizerTextEmbedding3SmallRequest.Raw
        | OpenAiVectorizerTextEmbedding3LargeRequest.Raw
        | OpenAiVectorizerTextEmbeddingAda002Request.Raw
        | BasicVectorizerIntfloatMultilingualE5LargeRequest.Raw
        | BasicVectorizerSentenceTransformersMultiQaMpnetBaseCosV1Request.Raw
        | BasicVectorizerSentenceTransformersMultiQaMpnetBaseDotV1Request.Raw
        | HkunlpInstructorXlVectorizerRequest.Raw
        | GoogleVertexAiVectorizerTextEmbedding004Request.Raw
        | GoogleVertexAiVectorizerTextMultilingualEmbedding002Request.Raw
        | GoogleVertexAiVectorizerGeminiEmbedding001Request.Raw
        | FastEmbedVectorizerBaaiBgeSmallEnV15Request.Raw
        | PrivateVectorizerRequest.Raw;
}
