/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { InitiatedPromptExecutionMeta } from "./InitiatedPromptExecutionMeta";

export const InitiatedExecutePromptEvent: core.serialization.ObjectSchema<
    serializers.InitiatedExecutePromptEvent.Raw,
    Vellum.InitiatedExecutePromptEvent
> = core.serialization.object({
    meta: InitiatedPromptExecutionMeta.optional(),
    executionId: core.serialization.property("execution_id", core.serialization.string()),
});

export declare namespace InitiatedExecutePromptEvent {
    interface Raw {
        meta?: InitiatedPromptExecutionMeta.Raw | null;
        execution_id: string;
    }
}
