/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const InitiatedEnum: core.serialization.Schema<serializers.InitiatedEnum.Raw, Vellum.InitiatedEnum> =
    core.serialization.stringLiteral("INITIATED");

export declare namespace InitiatedEnum {
    type Raw = "INITIATED";
}
