/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const IntegrationAuthConfigIntegrationCredential: core.serialization.ObjectSchema<
    serializers.IntegrationAuthConfigIntegrationCredential.Raw,
    Vellum.IntegrationAuthConfigIntegrationCredential
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace IntegrationAuthConfigIntegrationCredential {
    export interface Raw {
        id: string;
    }
}
