/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumValueRequest } from "./VellumValueRequest";

export const MetadataResolverVariableRequest: core.serialization.ObjectSchema<
    serializers.MetadataResolverVariableRequest.Raw,
    Vellum.MetadataResolverVariableRequest
> = core.serialization.object({
    value: VellumValueRequest,
    id: core.serialization.string(),
});

export declare namespace MetadataResolverVariableRequest {
    interface Raw {
        value: VellumValueRequest.Raw;
        id: string;
    }
}
