/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { StringInput } from "./StringInput";
import { JsonInput } from "./JsonInput";
import { ChatHistoryInput } from "./ChatHistoryInput";
import { NumberInput } from "./NumberInput";

export const MetricDefinitionInput: core.serialization.Schema<
    serializers.MetricDefinitionInput.Raw,
    Vellum.MetricDefinitionInput
> = core.serialization
    .union("type", {
        STRING: StringInput,
        JSON: JsonInput,
        CHAT_HISTORY: ChatHistoryInput,
        NUMBER: NumberInput,
    })
    .transform<Vellum.MetricDefinitionInput>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace MetricDefinitionInput {
    export type Raw =
        | MetricDefinitionInput.String
        | MetricDefinitionInput.Json
        | MetricDefinitionInput.ChatHistory
        | MetricDefinitionInput.Number;

    export interface String extends StringInput.Raw {
        type: "STRING";
    }

    export interface Json extends JsonInput.Raw {
        type: "JSON";
    }

    export interface ChatHistory extends ChatHistoryInput.Raw {
        type: "CHAT_HISTORY";
    }

    export interface Number extends NumberInput.Raw {
        type: "NUMBER";
    }
}
