/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { HuggingFaceTokenizerConfig } from "./HuggingFaceTokenizerConfig";
import { TikTokenTokenizerConfig } from "./TikTokenTokenizerConfig";

export const MlModelTokenizerConfig: core.serialization.Schema<
    serializers.MlModelTokenizerConfig.Raw,
    Vellum.MlModelTokenizerConfig
> = core.serialization.undiscriminatedUnion([HuggingFaceTokenizerConfig, TikTokenTokenizerConfig]);

export declare namespace MlModelTokenizerConfig {
    type Raw = HuggingFaceTokenizerConfig.Raw | TikTokenTokenizerConfig.Raw;
}
