/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const MlModelDeveloper: core.serialization.Schema<serializers.MlModelDeveloper.Raw, Vellum.MlModelDeveloper> =
    core.serialization.enum_([
        "01_AI",
        "AMAZON",
        "ANTHROPIC",
        "COHERE",
        "ELUTHERAI",
        "FIREWORKS_AI",
        "GOOGLE",
        "HUGGINGFACE",
        "IBM",
        "META",
        "MISTRAL_AI",
        "MOSAICML",
        "NOUS_RESEARCH",
        "OPENAI",
        "OPENCHAT",
        "OPENPIPE",
        "TII",
        "WIZARDLM",
    ]);

export declare namespace MlModelDeveloper {
    type Raw =
        | "01_AI"
        | "AMAZON"
        | "ANTHROPIC"
        | "COHERE"
        | "ELUTHERAI"
        | "FIREWORKS_AI"
        | "GOOGLE"
        | "HUGGINGFACE"
        | "IBM"
        | "META"
        | "MISTRAL_AI"
        | "MOSAICML"
        | "NOUS_RESEARCH"
        | "OPENAI"
        | "OPENCHAT"
        | "OPENPIPE"
        | "TII"
        | "WIZARDLM";
}
