/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const MlModelRead: core.serialization.ObjectSchema<serializers.MlModelRead.Raw, Vellum.MlModelRead> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        introducedOn: core.serialization.property("introduced_on", core.serialization.date()),
    });

export declare namespace MlModelRead {
    export interface Raw {
        id: string;
        name: string;
        introduced_on: string;
    }
}
