/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { VellumApi } from "@fern-api/vellum";
import * as core from "../../core";

export const ModelVersionBuildConfig: core.serialization.ObjectSchema<
    serializers.ModelVersionBuildConfig.Raw,
    VellumApi.ModelVersionBuildConfig
> = core.serialization.object({
    baseModel: core.serialization.property("base_model", core.serialization.string()),
    sandboxSnapshot: core.serialization.property(
        "sandbox_snapshot",
        core.serialization.lazyObject(async () => (await import("..")).ModelVersionSandboxSnapshot).optional()
    ),
});

export declare namespace ModelVersionBuildConfig {
    interface Raw {
        base_model: string;
        sandbox_snapshot?: serializers.ModelVersionSandboxSnapshot.Raw | null;
    }
}
