/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumVideoRequest } from "./VellumVideoRequest";

export const NamedTestCaseVideoVariableValueRequest: core.serialization.ObjectSchema<
    serializers.NamedTestCaseVideoVariableValueRequest.Raw,
    Vellum.NamedTestCaseVideoVariableValueRequest
> = core.serialization.object({
    value: VellumVideoRequest.nullable(),
    name: core.serialization.string(),
});

export declare namespace NamedTestCaseVideoVariableValueRequest {
    export interface Raw {
        value: VellumVideoRequest.Raw | null;
        name: string;
    }
}
