/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { FunctionCallRequest } from "./FunctionCallRequest";

export const NamedTestCaseFunctionCallVariableValueRequest: core.serialization.ObjectSchema<
    serializers.NamedTestCaseFunctionCallVariableValueRequest.Raw,
    Vellum.NamedTestCaseFunctionCallVariableValueRequest
> = core.serialization.object({
    type: core.serialization.stringLiteral("FUNCTION_CALL"),
    value: FunctionCallRequest.optional(),
    name: core.serialization.string(),
});

export declare namespace NamedTestCaseFunctionCallVariableValueRequest {
    interface Raw {
        type: "FUNCTION_CALL";
        value?: FunctionCallRequest.Raw | null;
        name: string;
    }
}
