/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const NamedScenarioInputStringVariableValueRequest: core.serialization.ObjectSchema<
    serializers.NamedScenarioInputStringVariableValueRequest.Raw,
    Vellum.NamedScenarioInputStringVariableValueRequest
> = core.serialization.object({
    value: core.serialization.string().nullable(),
    name: core.serialization.string(),
});

export declare namespace NamedScenarioInputStringVariableValueRequest {
    export interface Raw {
        value: string | null;
        name: string;
    }
}
