/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const NamedTestCaseSearchResultsVariableValueRequest: core.serialization.ObjectSchema<
    serializers.NamedTestCaseSearchResultsVariableValueRequest.Raw,
    Vellum.NamedTestCaseSearchResultsVariableValueRequest
> = core.serialization.object({
    name: core.serialization.string(),
    value: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).SearchResultRequest))
        .optional(),
});

export declare namespace NamedTestCaseSearchResultsVariableValueRequest {
    interface Raw {
        name: string;
        value?: serializers.SearchResultRequest.Raw[] | null;
    }
}
