/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumDocumentRequest } from "./VellumDocumentRequest";

export const NamedTestCaseDocumentVariableValueRequest: core.serialization.ObjectSchema<
    serializers.NamedTestCaseDocumentVariableValueRequest.Raw,
    Vellum.NamedTestCaseDocumentVariableValueRequest
> = core.serialization.object({
    value: VellumDocumentRequest.nullable(),
    name: core.serialization.string(),
});

export declare namespace NamedTestCaseDocumentVariableValueRequest {
    export interface Raw {
        value: VellumDocumentRequest.Raw | null;
        name: string;
    }
}
