/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumVideo } from "./VellumVideo";

export const NamedTestCaseVideoVariableValue: core.serialization.ObjectSchema<
    serializers.NamedTestCaseVideoVariableValue.Raw,
    Vellum.NamedTestCaseVideoVariableValue
> = core.serialization.object({
    value: VellumVideo.nullable(),
    name: core.serialization.string(),
});

export declare namespace NamedTestCaseVideoVariableValue {
    export interface Raw {
        value: VellumVideo.Raw | null;
        name: string;
    }
}
