/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ChatMessage } from "./ChatMessage";

export const NamedTestCaseChatHistoryVariableValue: core.serialization.ObjectSchema<
    serializers.NamedTestCaseChatHistoryVariableValue.Raw,
    Vellum.NamedTestCaseChatHistoryVariableValue
> = core.serialization.object({
    value: core.serialization.list(ChatMessage).optional(),
    name: core.serialization.string(),
});

export declare namespace NamedTestCaseChatHistoryVariableValue {
    interface Raw {
        value?: ChatMessage.Raw[] | null;
        name: string;
    }
}
