/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { WorkflowNodeResultEventState } from "./WorkflowNodeResultEventState";

export const NodeOutputCompiledArrayValue: core.serialization.ObjectSchema<
    serializers.NodeOutputCompiledArrayValue.Raw,
    Vellum.NodeOutputCompiledArrayValue
> = core.serialization.object({
    type: core.serialization.stringLiteral("ARRAY"),
    value: core.serialization.list(core.serialization.lazy(() => serializers.VellumValue)).optional(),
    nodeOutputId: core.serialization.property("node_output_id", core.serialization.string()),
    state: WorkflowNodeResultEventState.optional(),
});

export declare namespace NodeOutputCompiledArrayValue {
    interface Raw {
        type: "ARRAY";
        value?: serializers.VellumValue.Raw[] | null;
        node_output_id: string;
        state?: WorkflowNodeResultEventState.Raw | null;
    }
}
