/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { NodeOutputCompiledStringValue } from "./NodeOutputCompiledStringValue";
import { NodeOutputCompiledNumberValue } from "./NodeOutputCompiledNumberValue";
import { NodeOutputCompiledJsonValue } from "./NodeOutputCompiledJsonValue";
import { NodeOutputCompiledChatHistoryValue } from "./NodeOutputCompiledChatHistoryValue";
import { NodeOutputCompiledSearchResultsValue } from "./NodeOutputCompiledSearchResultsValue";
import { NodeOutputCompiledErrorValue } from "./NodeOutputCompiledErrorValue";
import { NodeOutputCompiledArrayValue } from "./NodeOutputCompiledArrayValue";
import { NodeOutputCompiledFunctionCallValue } from "./NodeOutputCompiledFunctionCallValue";
import { NodeOutputCompiledThinkingValue } from "./NodeOutputCompiledThinkingValue";

export const NodeOutputCompiledValue: core.serialization.Schema<
    serializers.NodeOutputCompiledValue.Raw,
    Vellum.NodeOutputCompiledValue
> = core.serialization
    .union("type", {
        STRING: NodeOutputCompiledStringValue,
        NUMBER: NodeOutputCompiledNumberValue,
        JSON: NodeOutputCompiledJsonValue,
        CHAT_HISTORY: NodeOutputCompiledChatHistoryValue,
        SEARCH_RESULTS: NodeOutputCompiledSearchResultsValue,
        ERROR: NodeOutputCompiledErrorValue,
        ARRAY: NodeOutputCompiledArrayValue,
        FUNCTION_CALL: NodeOutputCompiledFunctionCallValue,
        THINKING: NodeOutputCompiledThinkingValue,
    })
    .transform<Vellum.NodeOutputCompiledValue>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace NodeOutputCompiledValue {
    export type Raw =
        | NodeOutputCompiledValue.String
        | NodeOutputCompiledValue.Number
        | NodeOutputCompiledValue.Json
        | NodeOutputCompiledValue.ChatHistory
        | NodeOutputCompiledValue.SearchResults
        | NodeOutputCompiledValue.Error
        | NodeOutputCompiledValue.Array
        | NodeOutputCompiledValue.FunctionCall
        | NodeOutputCompiledValue.Thinking;

    export interface String extends NodeOutputCompiledStringValue.Raw {
        type: "STRING";
    }

    export interface Number extends NodeOutputCompiledNumberValue.Raw {
        type: "NUMBER";
    }

    export interface Json extends NodeOutputCompiledJsonValue.Raw {
        type: "JSON";
    }

    export interface ChatHistory extends NodeOutputCompiledChatHistoryValue.Raw {
        type: "CHAT_HISTORY";
    }

    export interface SearchResults extends NodeOutputCompiledSearchResultsValue.Raw {
        type: "SEARCH_RESULTS";
    }

    export interface Error extends NodeOutputCompiledErrorValue.Raw {
        type: "ERROR";
    }

    export interface Array extends NodeOutputCompiledArrayValue.Raw {
        type: "ARRAY";
    }

    export interface FunctionCall extends NodeOutputCompiledFunctionCallValue.Raw {
        type: "FUNCTION_CALL";
    }

    export interface Thinking extends NodeOutputCompiledThinkingValue.Raw {
        type: "THINKING";
    }
}
