/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const NodeOutputCompiledArrayValue: core.serialization.ObjectSchema<
    serializers.NodeOutputCompiledArrayValue.Raw,
    Vellum.NodeOutputCompiledArrayValue
> = core.serialization.object({
    nodeOutputId: core.serialization.property("node_output_id", core.serialization.string()),
    value: core.serialization.list(core.serialization.lazy(async () => (await import("..")).ArrayVariableValueItem)),
});

export declare namespace NodeOutputCompiledArrayValue {
    interface Raw {
        node_output_id: string;
        value: serializers.ArrayVariableValueItem.Raw[];
    }
}
