/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const OpenApiOneOfProperty: core.serialization.ObjectSchema<
    serializers.OpenApiOneOfProperty.Raw,
    Vellum.OpenApiOneOfProperty
> = core.serialization.object({
    oneOf: core.serialization.list(core.serialization.lazy(() => serializers.OpenApiProperty)),
    title: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
});

export declare namespace OpenApiOneOfProperty {
    interface Raw {
        oneOf: serializers.OpenApiProperty.Raw[];
        title?: string | null;
        description?: string | null;
    }
}
