/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";
import { OpenAiVectorizerConfig } from "./OpenAiVectorizerConfig";

export const OpenAiVectorizerTextEmbedding3Large: core.serialization.ObjectSchema<
    serializers.OpenAiVectorizerTextEmbedding3Large.Raw,
    Vellum.OpenAiVectorizerTextEmbedding3Large
> = core.serialization.object({
    config: OpenAiVectorizerConfig,
});

export declare namespace OpenAiVectorizerTextEmbedding3Large {
    interface Raw {
        config: OpenAiVectorizerConfig.Raw;
    }
}
