/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { OpenAiVectorizerConfigRequest } from "./OpenAiVectorizerConfigRequest";

export const OpenAiVectorizerTextEmbedding3SmallRequest: core.serialization.ObjectSchema<
    serializers.OpenAiVectorizerTextEmbedding3SmallRequest.Raw,
    Vellum.OpenAiVectorizerTextEmbedding3SmallRequest
> = core.serialization.object({
    config: OpenAiVectorizerConfigRequest,
    modelName: core.serialization.property("model_name", core.serialization.stringLiteral("text-embedding-3-small")),
});

export declare namespace OpenAiVectorizerTextEmbedding3SmallRequest {
    interface Raw {
        config: OpenAiVectorizerConfigRequest.Raw;
        model_name: "text-embedding-3-small";
    }
}
