/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { DeploymentReleaseTagRead } from "./DeploymentReleaseTagRead";

export const PaginatedDeploymentReleaseTagReadList: core.serialization.ObjectSchema<
    serializers.PaginatedDeploymentReleaseTagReadList.Raw,
    Vellum.PaginatedDeploymentReleaseTagReadList
> = core.serialization.object({
    count: core.serialization.number().optional(),
    next: core.serialization.string().optionalNullable(),
    previous: core.serialization.string().optionalNullable(),
    results: core.serialization.list(DeploymentReleaseTagRead).optional(),
});

export declare namespace PaginatedDeploymentReleaseTagReadList {
    export interface Raw {
        count?: number | null;
        next?: (string | null) | null;
        previous?: (string | null) | null;
        results?: DeploymentReleaseTagRead.Raw[] | null;
    }
}
