/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { SlimDocument } from "./SlimDocument";

export const PaginatedSlimDocumentList: core.serialization.ObjectSchema<
    serializers.PaginatedSlimDocumentList.Raw,
    Vellum.PaginatedSlimDocumentList
> = core.serialization.object({
    count: core.serialization.number().optional(),
    next: core.serialization.string().optionalNullable(),
    previous: core.serialization.string().optionalNullable(),
    results: core.serialization.list(SlimDocument).optional(),
});

export declare namespace PaginatedSlimDocumentList {
    export interface Raw {
        count?: number | null;
        next?: (string | null) | null;
        previous?: (string | null) | null;
        results?: SlimDocument.Raw[] | null;
    }
}
