/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const PdfSearchResultMetaSourceRequest: core.serialization.ObjectSchema<
    serializers.PdfSearchResultMetaSourceRequest.Raw,
    Vellum.PdfSearchResultMetaSourceRequest
> = core.serialization.object({
    startPageNum: core.serialization.property("start_page_num", core.serialization.number().optional()),
    endPageNum: core.serialization.property("end_page_num", core.serialization.number().optional()),
});

export declare namespace PdfSearchResultMetaSourceRequest {
    interface Raw {
        start_page_num?: number | null;
        end_page_num?: number | null;
    }
}
