/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const PromptVersionBuildConfigSandbox: core.serialization.ObjectSchema<
    serializers.PromptVersionBuildConfigSandbox.Raw,
    Vellum.PromptVersionBuildConfigSandbox
> = core.serialization.object({
    sandboxId: core.serialization.property("sandbox_id", core.serialization.string()),
    sandboxSnapshotId: core.serialization.property("sandbox_snapshot_id", core.serialization.string()),
    promptId: core.serialization.property("prompt_id", core.serialization.string()),
});

export declare namespace PromptVersionBuildConfigSandbox {
    export interface Raw {
        sandbox_id: string;
        sandbox_snapshot_id: string;
        prompt_id: string;
    }
}
