/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const PromptDeploymentReleasePromptDeployment: core.serialization.ObjectSchema<
    serializers.PromptDeploymentReleasePromptDeployment.Raw,
    Vellum.PromptDeploymentReleasePromptDeployment
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace PromptDeploymentReleasePromptDeployment {
    export interface Raw {
        name: string;
    }
}
