/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const PromptDeploymentReleasePromptVersion: core.serialization.ObjectSchema<
    serializers.PromptDeploymentReleasePromptVersion.Raw,
    Vellum.PromptDeploymentReleasePromptVersion
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace PromptDeploymentReleasePromptVersion {
    export interface Raw {
        id: string;
    }
}
