/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumAudio } from "./VellumAudio";

export const PromptRequestAudioInput: core.serialization.ObjectSchema<
    serializers.PromptRequestAudioInput.Raw,
    Vellum.PromptRequestAudioInput
> = core.serialization.object({
    key: core.serialization.string(),
    type: core.serialization.stringLiteral("AUDIO"),
    value: VellumAudio,
});

export declare namespace PromptRequestAudioInput {
    export interface Raw {
        key: string;
        type: "AUDIO";
        value: VellumAudio.Raw;
    }
}
