/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const PromptTemplateInputVariableRequest: core.serialization.ObjectSchema<
    serializers.PromptTemplateInputVariableRequest.Raw,
    Vellum.PromptTemplateInputVariableRequest
> = core.serialization.object({
    key: core.serialization.string(),
});

export declare namespace PromptTemplateInputVariableRequest {
    interface Raw {
        key: string;
    }
}
