/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const PromptDeploymentExpandMetaRequest: core.serialization.ObjectSchema<
    serializers.PromptDeploymentExpandMetaRequest.Raw,
    Vellum.PromptDeploymentExpandMetaRequest
> = core.serialization.object({
    modelName: core.serialization.property("model_name", core.serialization.boolean().optionalNullable()),
    usage: core.serialization.boolean().optionalNullable(),
    cost: core.serialization.boolean().optionalNullable(),
    finishReason: core.serialization.property("finish_reason", core.serialization.boolean().optionalNullable()),
    latency: core.serialization.boolean().optionalNullable(),
    deploymentReleaseTag: core.serialization.property(
        "deployment_release_tag",
        core.serialization.boolean().optionalNullable(),
    ),
    promptVersionId: core.serialization.property("prompt_version_id", core.serialization.boolean().optionalNullable()),
});

export declare namespace PromptDeploymentExpandMetaRequest {
    export interface Raw {
        model_name?: (boolean | null) | null;
        usage?: (boolean | null) | null;
        cost?: (boolean | null) | null;
        finish_reason?: (boolean | null) | null;
        latency?: (boolean | null) | null;
        deployment_release_tag?: (boolean | null) | null;
        prompt_version_id?: (boolean | null) | null;
    }
}
