/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const PromptTemplateBlockProperties: core.serialization.ObjectSchema<
    serializers.PromptTemplateBlockProperties.Raw,
    Vellum.PromptTemplateBlockProperties
> = core.serialization.object({
    chatRole: core.serialization.property(
        "chat_role",
        core.serialization.lazy(async () => (await import("..")).ChatMessageRole).optional()
    ),
    template: core.serialization.string().optional(),
    blocks: core.serialization
        .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
        .optional(),
});

export declare namespace PromptTemplateBlockProperties {
    interface Raw {
        chat_role?: serializers.ChatMessageRole.Raw | null;
        template?: string | null;
        blocks?: Record<string, unknown>[] | null;
    }
}
