/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const PromptDeploymentInputRequest: core.serialization.Schema<
    serializers.PromptDeploymentInputRequest.Raw,
    Vellum.PromptDeploymentInputRequest
> = core.serialization
    .union("type", {
        STRING: core.serialization.lazyObject(async () => (await import("..")).StringInputRequest),
        JSON: core.serialization.lazyObject(async () => (await import("..")).JsonInputRequest),
        CHAT_HISTORY: core.serialization.lazyObject(async () => (await import("..")).ChatHistoryInputRequest),
    })
    .transform<Vellum.PromptDeploymentInputRequest>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace PromptDeploymentInputRequest {
    type Raw =
        | PromptDeploymentInputRequest.String
        | PromptDeploymentInputRequest.Json
        | PromptDeploymentInputRequest.ChatHistory;

    interface String extends serializers.StringInputRequest.Raw {
        type: "STRING";
    }

    interface Json extends serializers.JsonInputRequest.Raw {
        type: "JSON";
    }

    interface ChatHistory extends serializers.ChatHistoryInputRequest.Raw {
        type: "CHAT_HISTORY";
    }
}
