/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumVideo } from "./VellumVideo";

export const PromptRequestVideoInput: core.serialization.ObjectSchema<
    serializers.PromptRequestVideoInput.Raw,
    Vellum.PromptRequestVideoInput
> = core.serialization.object({
    key: core.serialization.string(),
    type: core.serialization.stringLiteral("VIDEO"),
    value: VellumVideo,
});

export declare namespace PromptRequestVideoInput {
    export interface Raw {
        key: string;
        type: "VIDEO";
        value: VellumVideo.Raw;
    }
}
