/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ComponentsSchemasPromptVersionBuildConfigSandbox } from "./ComponentsSchemasPromptVersionBuildConfigSandbox";

export const PromptDeploymentReleasePromptVersion: core.serialization.ObjectSchema<
    serializers.PromptDeploymentReleasePromptVersion.Raw,
    Vellum.PromptDeploymentReleasePromptVersion
> = core.serialization.object({
    id: core.serialization.string().optional(),
    buildConfig: core.serialization.property(
        "build_config",
        ComponentsSchemasPromptVersionBuildConfigSandbox.optional(),
    ),
});

export declare namespace PromptDeploymentReleasePromptVersion {
    export interface Raw {
        id?: string | null;
        build_config?: ComponentsSchemasPromptVersionBuildConfigSandbox.Raw | null;
    }
}
