/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ReductoChunkerConfigRequest } from "./ReductoChunkerConfigRequest";

export const ReductoChunkingRequest: core.serialization.ObjectSchema<
    serializers.ReductoChunkingRequest.Raw,
    Vellum.ReductoChunkingRequest
> = core.serialization.object({
    chunkerName: core.serialization.property("chunker_name", core.serialization.stringLiteral("reducto-chunker")),
    chunkerConfig: core.serialization.property("chunker_config", ReductoChunkerConfigRequest.optional()),
});

export declare namespace ReductoChunkingRequest {
    export interface Raw {
        chunker_name: "reducto-chunker";
        chunker_config?: ReductoChunkerConfigRequest.Raw | null;
    }
}
