/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const ReductoChunkerEnum: core.serialization.Schema<
    serializers.ReductoChunkerEnum.Raw,
    Vellum.ReductoChunkerEnum
> = core.serialization.stringLiteral("reducto-chunker");

export declare namespace ReductoChunkerEnum {
    type Raw = "reducto-chunker";
}
