/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const RegisteredPromptModelVersion: core.serialization.ObjectSchema<
    serializers.RegisteredPromptModelVersion.Raw,
    Vellum.RegisteredPromptModelVersion
> = core.serialization.object({
    id: core.serialization.string(),
    label: core.serialization.string(),
});

export declare namespace RegisteredPromptModelVersion {
    interface Raw {
        id: string;
        label: string;
    }
}
