/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const RejectedExecutePromptResponse: core.serialization.ObjectSchema<
    serializers.RejectedExecutePromptResponse.Raw,
    Vellum.RejectedExecutePromptResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("..")).PromptExecutionMeta).optional(),
    raw: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    executionId: core.serialization.property("execution_id", core.serialization.string()),
    error: core.serialization.lazyObject(async () => (await import("..")).VellumError),
});

export declare namespace RejectedExecutePromptResponse {
    interface Raw {
        meta?: serializers.PromptExecutionMeta.Raw | null;
        raw?: Record<string, unknown> | null;
        execution_id: string;
        error: serializers.VellumError.Raw;
    }
}
