/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const ReleaseReviewReviewer: core.serialization.ObjectSchema<
    serializers.ReleaseReviewReviewer.Raw,
    Vellum.ReleaseReviewReviewer
> = core.serialization.object({
    id: core.serialization.string().optional(),
    fullName: core.serialization.property("full_name", core.serialization.string().optional()),
});

export declare namespace ReleaseReviewReviewer {
    export interface Raw {
        id?: string | null;
        full_name?: string | null;
    }
}
