/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VariablePromptBlock } from "./VariablePromptBlock";
import { PlainTextPromptBlock } from "./PlainTextPromptBlock";

export const RichTextChildBlock: core.serialization.Schema<
    serializers.RichTextChildBlock.Raw,
    Vellum.RichTextChildBlock
> = core.serialization
    .union(core.serialization.discriminant("blockType", "block_type"), {
        VARIABLE: VariablePromptBlock,
        PLAIN_TEXT: PlainTextPromptBlock,
    })
    .transform<Vellum.RichTextChildBlock>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace RichTextChildBlock {
    export type Raw = RichTextChildBlock.Variable | RichTextChildBlock.PlainText;

    export interface Variable extends VariablePromptBlock.Raw {
        block_type: "VARIABLE";
    }

    export interface PlainText extends PlainTextPromptBlock.Raw {
        block_type: "PLAIN_TEXT";
    }
}
