/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { RichTextChildBlockRequest } from "./RichTextChildBlockRequest";
import { PromptBlockState } from "./PromptBlockState";
import { EphemeralPromptCacheConfigRequest } from "./EphemeralPromptCacheConfigRequest";

export const RichTextPromptBlockRequest: core.serialization.ObjectSchema<
    serializers.RichTextPromptBlockRequest.Raw,
    Vellum.RichTextPromptBlockRequest
> = core.serialization.object({
    blockType: core.serialization.property("block_type", core.serialization.stringLiteral("RICH_TEXT")),
    blocks: core.serialization.list(RichTextChildBlockRequest),
    id: core.serialization.string(),
    state: PromptBlockState.optional(),
    cacheConfig: core.serialization.property("cache_config", EphemeralPromptCacheConfigRequest.optional()),
});

export declare namespace RichTextPromptBlockRequest {
    interface Raw {
        block_type: "RICH_TEXT";
        blocks: RichTextChildBlockRequest.Raw[];
        id: string;
        state?: PromptBlockState.Raw | null;
        cache_config?: EphemeralPromptCacheConfigRequest.Raw | null;
    }
}
