/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ScenarioInput } from "./ScenarioInput";

export const SandboxScenario: core.serialization.ObjectSchema<serializers.SandboxScenario.Raw, Vellum.SandboxScenario> =
    core.serialization.object({
        label: core.serialization.string().optional(),
        inputs: core.serialization.list(ScenarioInput),
        id: core.serialization.string(),
    });

export declare namespace SandboxScenario {
    interface Raw {
        label?: string | null;
        inputs: ScenarioInput.Raw[];
        id: string;
    }
}
