/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumDocument } from "./VellumDocument";

export const ScenarioInputDocumentVariableValue: core.serialization.ObjectSchema<
    serializers.ScenarioInputDocumentVariableValue.Raw,
    Vellum.ScenarioInputDocumentVariableValue
> = core.serialization.object({
    value: VellumDocument.nullable(),
    inputVariableId: core.serialization.property("input_variable_id", core.serialization.string()),
});

export declare namespace ScenarioInputDocumentVariableValue {
    export interface Raw {
        value: VellumDocument.Raw | null;
        input_variable_id: string;
    }
}
