/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const SearchResultsEnum: core.serialization.Schema<serializers.SearchResultsEnum.Raw, Vellum.SearchResultsEnum> =
    core.serialization.stringLiteral("SEARCH_RESULTS");

export declare namespace SearchResultsEnum {
    type Raw = "SEARCH_RESULTS";
}
