/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const SearchResultDocumentRequest: core.serialization.ObjectSchema<
    serializers.SearchResultDocumentRequest.Raw,
    Vellum.SearchResultDocumentRequest
> = core.serialization.object({
    id: core.serialization.string().optional(),
    label: core.serialization.string(),
    externalId: core.serialization.property("external_id", core.serialization.string().optional()),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace SearchResultDocumentRequest {
    interface Raw {
        id?: string | null;
        label: string;
        external_id?: string | null;
        metadata?: Record<string, unknown> | null;
    }
}
