/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { SearchResultRequest } from "./SearchResultRequest";

export const SearchResultsVellumValueRequest: core.serialization.ObjectSchema<
    serializers.SearchResultsVellumValueRequest.Raw,
    Vellum.SearchResultsVellumValueRequest
> = core.serialization.object({
    type: core.serialization.stringLiteral("SEARCH_RESULTS"),
    value: core.serialization.list(SearchResultRequest).optional(),
});

export declare namespace SearchResultsVellumValueRequest {
    interface Raw {
        type: "SEARCH_RESULTS";
        value?: SearchResultRequest.Raw[] | null;
    }
}
