/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { SearchResult } from "./SearchResult";

export const SearchResponse: core.serialization.ObjectSchema<serializers.SearchResponse.Raw, Vellum.SearchResponse> =
    core.serialization.object({
        results: core.serialization.list(SearchResult),
    });

export declare namespace SearchResponse {
    interface Raw {
        results: SearchResult.Raw[];
    }
}
