/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { SearchResultMetaSourceRequest } from "./SearchResultMetaSourceRequest";

export const SearchResultMetaRequest: core.serialization.ObjectSchema<
    serializers.SearchResultMetaRequest.Raw,
    Vellum.SearchResultMetaRequest
> = core.serialization.object({
    source: SearchResultMetaSourceRequest.optionalNullable(),
});

export declare namespace SearchResultMetaRequest {
    export interface Raw {
        source?: (SearchResultMetaSourceRequest.Raw | null) | null;
    }
}
