/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ReleaseReviewReviewer } from "./ReleaseReviewReviewer";
import { ReleaseReviewState } from "./ReleaseReviewState";

export const SlimReleaseReview: core.serialization.ObjectSchema<
    serializers.SlimReleaseReview.Raw,
    Vellum.SlimReleaseReview
> = core.serialization.object({
    id: core.serialization.string().optional(),
    created: core.serialization.date().optional(),
    reviewer: ReleaseReviewReviewer,
    state: ReleaseReviewState,
});

export declare namespace SlimReleaseReview {
    export interface Raw {
        id?: string | null;
        created?: string | null;
        reviewer: ReleaseReviewReviewer.Raw;
        state: ReleaseReviewState.Raw;
    }
}
