/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const StringVellumValueRequest: core.serialization.ObjectSchema<
    serializers.StringVellumValueRequest.Raw,
    Vellum.StringVellumValueRequest
> = core.serialization.object({
    type: core.serialization.stringLiteral("STRING"),
    value: core.serialization.string().optional(),
});

export declare namespace StringVellumValueRequest {
    interface Raw {
        type: "STRING";
        value?: string | null;
    }
}
