/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const StringChatMessageContentRequest: core.serialization.ObjectSchema<
    serializers.StringChatMessageContentRequest.Raw,
    Vellum.StringChatMessageContentRequest
> = core.serialization.object({
    type: core.serialization.stringLiteral("STRING"),
    value: core.serialization.string(),
});

export declare namespace StringChatMessageContentRequest {
    export interface Raw {
        type: "STRING";
        value: string;
    }
}
