/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const StringChatMessageContent: core.serialization.ObjectSchema<
    serializers.StringChatMessageContent.Raw,
    Vellum.StringChatMessageContent
> = core.serialization.object({
    type: core.serialization.stringLiteral("STRING"),
    value: core.serialization.string(),
});

export declare namespace StringChatMessageContent {
    interface Raw {
        type: "STRING";
        value: string;
    }
}
