/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const SubworkflowNodeResult: core.serialization.ObjectSchema<
    serializers.SubworkflowNodeResult.Raw,
    Vellum.SubworkflowNodeResult
> = core.serialization.object({});

export declare namespace SubworkflowNodeResult {
    interface Raw {}
}
