/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const TemplatingNodeChatHistoryResult: core.serialization.ObjectSchema<
    serializers.TemplatingNodeChatHistoryResult.Raw,
    Vellum.TemplatingNodeChatHistoryResult
> = core.serialization.object({
    id: core.serialization.string(),
    value: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).ChatMessage))
        .optional(),
});

export declare namespace TemplatingNodeChatHistoryResult {
    interface Raw {
        id: string;
        value?: serializers.ChatMessage.Raw[] | null;
    }
}
