/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ArrayVariableValueItem } from "./ArrayVariableValueItem";

export const TemplatingNodeArrayResult: core.serialization.ObjectSchema<
    serializers.TemplatingNodeArrayResult.Raw,
    Vellum.TemplatingNodeArrayResult
> = core.serialization.object({
    id: core.serialization.string(),
    type: core.serialization.stringLiteral("ARRAY"),
    value: core.serialization.list(ArrayVariableValueItem).optional(),
});

export declare namespace TemplatingNodeArrayResult {
    interface Raw {
        id: string;
        type: "ARRAY";
        value?: ArrayVariableValueItem.Raw[] | null;
    }
}
