/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const TerminalNodeChatHistoryResult: core.serialization.ObjectSchema<
    serializers.TerminalNodeChatHistoryResult.Raw,
    Vellum.TerminalNodeChatHistoryResult
> = core.serialization.object({
    name: core.serialization.string(),
    value: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).ChatMessage)),
});

export declare namespace TerminalNodeChatHistoryResult {
    interface Raw {
        name: string;
        value: serializers.ChatMessage.Raw[];
    }
}
