/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const TestCaseErrorVariableValueRequest: core.serialization.ObjectSchema<
    serializers.TestCaseErrorVariableValueRequest.Raw,
    Vellum.TestCaseErrorVariableValueRequest
> = core.serialization.object({
    variableId: core.serialization.property("variable_id", core.serialization.string()),
    value: core.serialization.lazyObject(async () => (await import("..")).VellumErrorRequest).optional(),
});

export declare namespace TestCaseErrorVariableValueRequest {
    interface Raw {
        variable_id: string;
        value?: serializers.VellumErrorRequest.Raw | null;
    }
}
