/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ChatMessage } from "./ChatMessage";

export const TestSuiteRunExecutionChatHistoryOutput: core.serialization.ObjectSchema<
    serializers.TestSuiteRunExecutionChatHistoryOutput.Raw,
    Vellum.TestSuiteRunExecutionChatHistoryOutput
> = core.serialization.object({
    name: core.serialization.string(),
    value: core.serialization.list(ChatMessage).nullable(),
    outputVariableId: core.serialization.property("output_variable_id", core.serialization.string()),
});

export declare namespace TestSuiteRunExecutionChatHistoryOutput {
    export interface Raw {
        name: string;
        value: ChatMessage.Raw[] | null;
        output_variable_id: string;
    }
}
