/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumAudio } from "./VellumAudio";

export const TestCaseAudioVariableValue: core.serialization.ObjectSchema<
    serializers.TestCaseAudioVariableValue.Raw,
    Vellum.TestCaseAudioVariableValue
> = core.serialization.object({
    variableId: core.serialization.property("variable_id", core.serialization.string()),
    name: core.serialization.string().optional(),
    type: core.serialization.stringLiteral("AUDIO"),
    value: VellumAudio,
});

export declare namespace TestCaseAudioVariableValue {
    export interface Raw {
        variable_id: string;
        name?: string | null;
        type: "AUDIO";
        value: VellumAudio.Raw;
    }
}
