/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const TestSuiteRunExecutionJsonOutput: core.serialization.ObjectSchema<
    serializers.TestSuiteRunExecutionJsonOutput.Raw,
    Vellum.TestSuiteRunExecutionJsonOutput
> = core.serialization.object({
    name: core.serialization.string(),
    value: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    outputVariableId: core.serialization.property("output_variable_id", core.serialization.string()),
});

export declare namespace TestSuiteRunExecutionJsonOutput {
    interface Raw {
        name: string;
        value?: Record<string, unknown> | null;
        output_variable_id: string;
    }
}
