/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { TestSuiteRunWorkflowReleaseTagExecConfigDataRequest } from "./TestSuiteRunWorkflowReleaseTagExecConfigDataRequest";

export const TestSuiteRunWorkflowReleaseTagExecConfigRequest: core.serialization.ObjectSchema<
    serializers.TestSuiteRunWorkflowReleaseTagExecConfigRequest.Raw,
    Vellum.TestSuiteRunWorkflowReleaseTagExecConfigRequest
> = core.serialization.object({
    data: TestSuiteRunWorkflowReleaseTagExecConfigDataRequest,
    testCaseIds: core.serialization.property(
        "test_case_ids",
        core.serialization.list(core.serialization.string()).optionalNullable(),
    ),
});

export declare namespace TestSuiteRunWorkflowReleaseTagExecConfigRequest {
    export interface Raw {
        data: TestSuiteRunWorkflowReleaseTagExecConfigDataRequest.Raw;
        test_case_ids?: (string[] | null) | null;
    }
}
