/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { TestSuiteRunDeploymentReleaseTagExecConfigData } from "./TestSuiteRunDeploymentReleaseTagExecConfigData";

export const TestSuiteRunDeploymentReleaseTagExecConfig: core.serialization.ObjectSchema<
    serializers.TestSuiteRunDeploymentReleaseTagExecConfig.Raw,
    Vellum.TestSuiteRunDeploymentReleaseTagExecConfig
> = core.serialization.object({
    type: core.serialization.stringLiteral("DEPLOYMENT_RELEASE_TAG"),
    data: TestSuiteRunDeploymentReleaseTagExecConfigData,
    testCaseIds: core.serialization.property(
        "test_case_ids",
        core.serialization.list(core.serialization.string()).optional(),
    ),
});

export declare namespace TestSuiteRunDeploymentReleaseTagExecConfig {
    export interface Raw {
        type: "DEPLOYMENT_RELEASE_TAG";
        data: TestSuiteRunDeploymentReleaseTagExecConfigData.Raw;
        test_case_ids?: string[] | null;
    }
}
