/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumImage } from "./VellumImage";

export const TestCaseImageVariableValue: core.serialization.ObjectSchema<
    serializers.TestCaseImageVariableValue.Raw,
    Vellum.TestCaseImageVariableValue
> = core.serialization.object({
    variableId: core.serialization.property("variable_id", core.serialization.string()),
    name: core.serialization.string().optional(),
    value: VellumImage.nullable(),
});

export declare namespace TestCaseImageVariableValue {
    export interface Raw {
        variable_id: string;
        name?: string | null;
        value: VellumImage.Raw | null;
    }
}
