/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const TestSuiteRunMetricNumberOutputTypeEnum: core.serialization.Schema<
    serializers.TestSuiteRunMetricNumberOutputTypeEnum.Raw,
    Vellum.TestSuiteRunMetricNumberOutputTypeEnum
> = core.serialization.stringLiteral("NUMBER");

export declare namespace TestSuiteRunMetricNumberOutputTypeEnum {
    type Raw = "NUMBER";
}
