/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { TestSuiteTestCaseReplacedBulkResultData } from "./TestSuiteTestCaseReplacedBulkResultData";

export const TestSuiteTestCaseReplacedBulkResult: core.serialization.ObjectSchema<
    serializers.TestSuiteTestCaseReplacedBulkResult.Raw,
    Vellum.TestSuiteTestCaseReplacedBulkResult
> = core.serialization.object({
    id: core.serialization.string(),
    data: TestSuiteTestCaseReplacedBulkResultData,
});

export declare namespace TestSuiteTestCaseReplacedBulkResult {
    interface Raw {
        id: string;
        data: TestSuiteTestCaseReplacedBulkResultData.Raw;
    }
}
