/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const TestSuiteRunExecutionMetricDefinition: core.serialization.ObjectSchema<
    serializers.TestSuiteRunExecutionMetricDefinition.Raw,
    Vellum.TestSuiteRunExecutionMetricDefinition
> = core.serialization.object({
    id: core.serialization.string().optional(),
    label: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
});

export declare namespace TestSuiteRunExecutionMetricDefinition {
    interface Raw {
        id?: string | null;
        label?: string | null;
        name?: string | null;
    }
}
