/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const TestSuiteRunExecutionNumberOutput: core.serialization.ObjectSchema<
    serializers.TestSuiteRunExecutionNumberOutput.Raw,
    Vellum.TestSuiteRunExecutionNumberOutput
> = core.serialization.object({
    name: core.serialization.string(),
    type: core.serialization.stringLiteral("NUMBER"),
    value: core.serialization.number().optionalNullable(),
    outputVariableId: core.serialization.property("output_variable_id", core.serialization.string()),
});

export declare namespace TestSuiteRunExecutionNumberOutput {
    export interface Raw {
        name: string;
        type: "NUMBER";
        value?: (number | null) | null;
        output_variable_id: string;
    }
}
