/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const TestSuiteRunWorkflowSandboxExecConfigDataRequest: core.serialization.ObjectSchema<
    serializers.TestSuiteRunWorkflowSandboxExecConfigDataRequest.Raw,
    Vellum.TestSuiteRunWorkflowSandboxExecConfigDataRequest
> = core.serialization.object({
    workflowSandboxId: core.serialization.property("workflow_sandbox_id", core.serialization.string()),
});

export declare namespace TestSuiteRunWorkflowSandboxExecConfigDataRequest {
    export interface Raw {
        workflow_sandbox_id: string;
    }
}
