/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { TestSuiteRunMetricStringOutput } from "./TestSuiteRunMetricStringOutput";
import { TestSuiteRunMetricNumberOutput } from "./TestSuiteRunMetricNumberOutput";
import { TestSuiteRunMetricErrorOutput } from "./TestSuiteRunMetricErrorOutput";

export const TestSuiteRunMetricOutput: core.serialization.Schema<
    serializers.TestSuiteRunMetricOutput.Raw,
    Vellum.TestSuiteRunMetricOutput
> = core.serialization.undiscriminatedUnion([
    TestSuiteRunMetricStringOutput,
    TestSuiteRunMetricNumberOutput,
    TestSuiteRunMetricErrorOutput,
]);

export declare namespace TestSuiteRunMetricOutput {
    type Raw =
        | TestSuiteRunMetricStringOutput.Raw
        | TestSuiteRunMetricNumberOutput.Raw
        | TestSuiteRunMetricErrorOutput.Raw;
}
