/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const TestCaseErrorVariableValue: core.serialization.ObjectSchema<
    serializers.TestCaseErrorVariableValue.Raw,
    Vellum.TestCaseErrorVariableValue
> = core.serialization.object({
    variableId: core.serialization.property("variable_id", core.serialization.string()),
    value: core.serialization.lazyObject(async () => (await import("..")).VellumError).optional(),
});

export declare namespace TestCaseErrorVariableValue {
    interface Raw {
        variable_id: string;
        value?: serializers.VellumError.Raw | null;
    }
}
