/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const TestSuiteRunMetricStringOutput: core.serialization.ObjectSchema<
    serializers.TestSuiteRunMetricStringOutput.Raw,
    Vellum.TestSuiteRunMetricStringOutput
> = core.serialization.object({
    value: core.serialization.string().optionalNullable(),
    type: core.serialization.stringLiteral("STRING"),
    name: core.serialization.string(),
});

export declare namespace TestSuiteRunMetricStringOutput {
    export interface Raw {
        value?: (string | null) | null;
        type: "STRING";
        name: string;
    }
}
