/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const TextEmbedding3LargeEnum: core.serialization.Schema<
    serializers.TextEmbedding3LargeEnum.Raw,
    Vellum.TextEmbedding3LargeEnum
> = core.serialization.stringLiteral("text-embedding-3-large");

export declare namespace TextEmbedding3LargeEnum {
    type Raw = "text-embedding-3-large";
}
