/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { PromptBlockState } from "./PromptBlockState";
import { EphemeralPromptCacheConfigRequest } from "./EphemeralPromptCacheConfigRequest";

export const VariablePromptBlockRequest: core.serialization.ObjectSchema<
    serializers.VariablePromptBlockRequest.Raw,
    Vellum.VariablePromptBlockRequest
> = core.serialization.object({
    state: PromptBlockState.optional(),
    cacheConfig: core.serialization.property("cache_config", EphemeralPromptCacheConfigRequest.optional()),
    blockType: core.serialization.property("block_type", core.serialization.stringLiteral("VARIABLE")),
    inputVariableId: core.serialization.property("input_variable_id", core.serialization.string()),
});

export declare namespace VariablePromptBlockRequest {
    interface Raw {
        state?: PromptBlockState.Raw | null;
        cache_config?: EphemeralPromptCacheConfigRequest.Raw | null;
        block_type: "VARIABLE";
        input_variable_id: string;
    }
}
