/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { WorkflowExecutionSpan } from "./WorkflowExecutionSpan";
import { NodeExecutionSpan } from "./NodeExecutionSpan";

export const VellumSpan: core.serialization.Schema<serializers.VellumSpan.Raw, Vellum.VellumSpan> =
    core.serialization.undiscriminatedUnion([WorkflowExecutionSpan, NodeExecutionSpan]);

export declare namespace VellumSpan {
    export type Raw = WorkflowExecutionSpan.Raw | NodeExecutionSpan.Raw;
}
