/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumVideoRequest } from "./VellumVideoRequest";

export const VideoChatMessageContentRequest: core.serialization.ObjectSchema<
    serializers.VideoChatMessageContentRequest.Raw,
    Vellum.VideoChatMessageContentRequest
> = core.serialization.object({
    type: core.serialization.stringLiteral("VIDEO"),
    value: VellumVideoRequest,
});

export declare namespace VideoChatMessageContentRequest {
    export interface Raw {
        type: "VIDEO";
        value: VellumVideoRequest.Raw;
    }
}
