/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { VellumVideoRequest } from "./VellumVideoRequest";

export const VideoVellumValueRequest: core.serialization.ObjectSchema<
    serializers.VideoVellumValueRequest.Raw,
    Vellum.VideoVellumValueRequest
> = core.serialization.object({
    type: core.serialization.stringLiteral("VIDEO"),
    value: VellumVideoRequest.optionalNullable(),
});

export declare namespace VideoVellumValueRequest {
    export interface Raw {
        type: "VIDEO";
        value?: (VellumVideoRequest.Raw | null) | null;
    }
}
