/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const WorkflowExecutionEventType: core.serialization.Schema<
    serializers.WorkflowExecutionEventType.Raw,
    Vellum.WorkflowExecutionEventType
> = core.serialization.enum_(["NODE", "WORKFLOW"]);

export declare namespace WorkflowExecutionEventType {
    type Raw = "NODE" | "WORKFLOW";
}
