/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const WorkflowReleaseTagEnum: core.serialization.Schema<
    serializers.WorkflowReleaseTagEnum.Raw,
    Vellum.WorkflowReleaseTagEnum
> = core.serialization.enum_(["WORKFLOW_RELEASE_TAG"]);

export declare namespace WorkflowReleaseTagEnum {
    export type Raw = "WORKFLOW_RELEASE_TAG";
}
