/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ExecutionVellumValue } from "./ExecutionVellumValue";

export const WorkflowExecutionActual: core.serialization.ObjectSchema<
    serializers.WorkflowExecutionActual.Raw,
    Vellum.WorkflowExecutionActual
> = core.serialization.object({
    output: ExecutionVellumValue,
    timestamp: core.serialization.date(),
    quality: core.serialization.number().optionalNullable(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).nullable(),
});

export declare namespace WorkflowExecutionActual {
    export interface Raw {
        output: ExecutionVellumValue.Raw;
        timestamp: string;
        quality?: (number | null) | null;
        metadata: Record<string, unknown> | null;
    }
}
