/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { WorkflowNodeResultEventState } from "./WorkflowNodeResultEventState";

export const WorkflowResultEventOutputDataArray: core.serialization.ObjectSchema<
    serializers.WorkflowResultEventOutputDataArray.Raw,
    Vellum.WorkflowResultEventOutputDataArray
> = core.serialization.object({
    id: core.serialization.string().optionalNullable(),
    name: core.serialization.string(),
    state: WorkflowNodeResultEventState,
    nodeId: core.serialization.property("node_id", core.serialization.string().optionalNullable()),
    delta: core.serialization.string().optionalNullable(),
    value: core.serialization.list(core.serialization.lazy(() => serializers.VellumValue)).nullable(),
});

export declare namespace WorkflowResultEventOutputDataArray {
    export interface Raw {
        id?: (string | null) | null;
        name: string;
        state: WorkflowNodeResultEventState.Raw;
        node_id?: (string | null) | null;
        delta?: (string | null) | null;
        value: serializers.VellumValue.Raw[] | null;
    }
}
