/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { ChatMessageRequest } from "./ChatMessageRequest";

export const WorkflowExecutionActualChatHistoryRequest: core.serialization.ObjectSchema<
    serializers.WorkflowExecutionActualChatHistoryRequest.Raw,
    Vellum.WorkflowExecutionActualChatHistoryRequest
> = core.serialization.object({
    outputId: core.serialization.property("output_id", core.serialization.string().optionalNullable()),
    outputKey: core.serialization.property("output_key", core.serialization.string().optionalNullable()),
    quality: core.serialization.number().optionalNullable(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    timestamp: core.serialization.number().optionalNullable(),
    desiredOutputValue: core.serialization.property(
        "desired_output_value",
        core.serialization.list(ChatMessageRequest).optionalNullable(),
    ),
});

export declare namespace WorkflowExecutionActualChatHistoryRequest {
    export interface Raw {
        output_id?: (string | null) | null;
        output_key?: (string | null) | null;
        quality?: (number | null) | null;
        metadata?: (Record<string, unknown> | null) | null;
        timestamp?: (number | null) | null;
        desired_output_value?: (ChatMessageRequest.Raw[] | null) | null;
    }
}
