/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";

export const WorkflowExecutionSpanAttributes: core.serialization.ObjectSchema<
    serializers.WorkflowExecutionSpanAttributes.Raw,
    Vellum.WorkflowExecutionSpanAttributes
> = core.serialization.object({
    label: core.serialization.string(),
});

export declare namespace WorkflowExecutionSpanAttributes {
    export interface Raw {
        label: string;
    }
}
