/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const WorkflowNodeResultEventStateEnum: core.serialization.Schema<
    serializers.WorkflowNodeResultEventStateEnum.Raw,
    Vellum.WorkflowNodeResultEventStateEnum
> = core.serialization.enum_(["INITIATED", "STREAMING", "FULFILLED", "REJECTED"]);

export declare namespace WorkflowNodeResultEventStateEnum {
    type Raw = "INITIATED" | "STREAMING" | "FULFILLED" | "REJECTED";
}
