/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vellum from "../../api";
import * as core from "../../core";

export const WorkflowExecutionWorkflowResultEvent: core.serialization.ObjectSchema<
    serializers.WorkflowExecutionWorkflowResultEvent.Raw,
    Vellum.WorkflowExecutionWorkflowResultEvent
> = core.serialization.object({
    runId: core.serialization.property("run_id", core.serialization.string()),
    externalId: core.serialization.property("external_id", core.serialization.string().optional()),
    data: core.serialization.lazyObject(async () => (await import("..")).WorkflowResultEvent),
});

export declare namespace WorkflowExecutionWorkflowResultEvent {
    interface Raw {
        run_id: string;
        external_id?: string | null;
        data: serializers.WorkflowResultEvent.Raw;
    }
}
