/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { WorkflowDisplayIcon } from "./WorkflowDisplayIcon";

export const WorkflowSandboxDisplayData: core.serialization.ObjectSchema<
    serializers.WorkflowSandboxDisplayData.Raw,
    Vellum.WorkflowSandboxDisplayData
> = core.serialization.object({
    icon: WorkflowDisplayIcon.optionalNullable(),
});

export declare namespace WorkflowSandboxDisplayData {
    export interface Raw {
        icon?: (WorkflowDisplayIcon.Raw | null) | null;
    }
}
