/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { MlModelUsageWrapper } from "./MlModelUsageWrapper";
import { Price } from "./Price";
import { WorkflowExecutionUsageCalculationError } from "./WorkflowExecutionUsageCalculationError";

export const WorkflowExecutionUsageResult: core.serialization.ObjectSchema<
    serializers.WorkflowExecutionUsageResult.Raw,
    Vellum.WorkflowExecutionUsageResult
> = core.serialization.object({
    usage: core.serialization.list(MlModelUsageWrapper).optional(),
    cost: core.serialization.list(Price).optional(),
    error: WorkflowExecutionUsageCalculationError.optional(),
});

export declare namespace WorkflowExecutionUsageResult {
    export interface Raw {
        usage?: MlModelUsageWrapper.Raw[] | null;
        cost?: Price.Raw[] | null;
        error?: WorkflowExecutionUsageCalculationError.Raw | null;
    }
}
