/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { SecretTypeEnum } from "./SecretTypeEnum";

export const WorkspaceSecretRead: core.serialization.ObjectSchema<
    serializers.WorkspaceSecretRead.Raw,
    Vellum.WorkspaceSecretRead
> = core.serialization.object({
    id: core.serialization.string(),
    modified: core.serialization.date(),
    name: core.serialization.string(),
    label: core.serialization.string(),
    secretType: core.serialization.property("secret_type", SecretTypeEnum),
});

export declare namespace WorkspaceSecretRead {
    interface Raw {
        id: string;
        modified: string;
        name: string;
        label: string;
        secret_type: SecretTypeEnum.Raw;
    }
}
