/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { WorkflowEventErrorRawData } from "./WorkflowEventErrorRawData";
import { WorkflowExecutionEventErrorCode } from "./WorkflowExecutionEventErrorCode";

export const WorkflowEventError: core.serialization.ObjectSchema<
    serializers.WorkflowEventError.Raw,
    Vellum.WorkflowEventError
> = core.serialization.object({
    message: core.serialization.string(),
    rawData: core.serialization.property("raw_data", WorkflowEventErrorRawData.optionalNullable()),
    code: WorkflowExecutionEventErrorCode,
    stacktrace: core.serialization.string().optionalNullable(),
});

export declare namespace WorkflowEventError {
    export interface Raw {
        message: string;
        raw_data?: (WorkflowEventErrorRawData.Raw | null) | null;
        code: WorkflowExecutionEventErrorCode.Raw;
        stacktrace?: (string | null) | null;
    }
}
