/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { WorkflowIntegrationDependency } from "./WorkflowIntegrationDependency";
import { WorkflowModelProviderDependency } from "./WorkflowModelProviderDependency";

export const WorkflowDependency: core.serialization.Schema<
    serializers.WorkflowDependency.Raw,
    Vellum.WorkflowDependency
> = core.serialization.undiscriminatedUnion([WorkflowIntegrationDependency, WorkflowModelProviderDependency]);

export declare namespace WorkflowDependency {
    export type Raw = WorkflowIntegrationDependency.Raw | WorkflowModelProviderDependency.Raw;
}
