/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vellum from "../../api/index";
import * as core from "../../core";
import { WorkflowNodeResultEventState } from "./WorkflowNodeResultEventState";

export const WorkflowResultEventOutputDataString: core.serialization.ObjectSchema<
    serializers.WorkflowResultEventOutputDataString.Raw,
    Vellum.WorkflowResultEventOutputDataString
> = core.serialization.object({
    id: core.serialization.string().optionalNullable(),
    name: core.serialization.string(),
    state: WorkflowNodeResultEventState,
    nodeId: core.serialization.property("node_id", core.serialization.string().optionalNullable()),
    delta: core.serialization.string().optionalNullable(),
    type: core.serialization.stringLiteral("STRING"),
    value: core.serialization.string().optionalNullable(),
});

export declare namespace WorkflowResultEventOutputDataString {
    export interface Raw {
        id?: (string | null) | null;
        name: string;
        state: WorkflowNodeResultEventState.Raw;
        node_id?: (string | null) | null;
        delta?: (string | null) | null;
        type: "STRING";
        value?: (string | null) | null;
    }
}
