/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../..";

export interface UpsertSandboxScenarioRequestRequest {
    label?: string;
    /** The inputs for the scenario */
    inputs: Vellum.ScenarioInputRequest[];
    /** The id of the scenario to update. If none is provided, an id will be generated and a new scenario will be appended. */
    scenarioId?: string;
    metricInputParams?: Vellum.SandboxMetricInputParamsRequest;
}
