/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UploadDocumentRequest {
    addToIndexNames?: string[];
    externalId?: string;
    label: string;
    keywords?: string[];
}
