/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entityId: "entity_id"
 *     }
 */
export interface AddEntityToFolderRequest {
    /** The ID of the entity you would like to move. */
    entityId: string;
}
