/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VellumEnvironmentUrls {
    default: string;
    predict: string;
    documents: string;
}

export const VellumEnvironment = {
    Production: {
        default: "https://api.vellum.ai",
        predict: "https://predict.vellum.ai",
        documents: "https://documents.vellum.ai",
    },
} as const;

export type VellumEnvironment = typeof VellumEnvironment.Production;
