/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../..";

export interface PatchedDocumentUpdateRequest {
    /** A human-readable label for the document. Defaults to the originally uploaded file's file name. <span style="white-space: nowrap">`non-empty`</span> <span style="white-space: nowrap">`<= 1000 characters`</span> */
    label?: string;
    /**
     * The current status of the document
     *
     * * `ACTIVE` - Active
     */
    status?: Vellum.DocumentStatus;
    /** A JSON object containing any metadata associated with the document that you'd like to filter upon later. */
    metadata?: Record<string, unknown>;
}
