/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../index";

/**
 * @example
 *     {}
 */
export interface PatchedDocumentUpdateRequest {
    /** A human-readable label for the document. Defaults to the originally uploaded file's file name. */
    label?: string;
    /**
     * The current status of the document
     *
     * * `ACTIVE` - Active
     */
    status?: Vellum.DocumentStatus;
    /** A list of keywords that'll be associated with the document. Used as part of keyword search. */
    keywords?: string[];
    /** A JSON object containing any metadata associated with the document that you'd like to filter upon later. */
    metadata?: Record<string, unknown> | null;
}
