/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         inputs: {
 *             "inputs": {
 *                 "key": "value"
 *             }
 *         }
 *     }
 */
export interface ExecuteWorkflowDeploymentStreamRequest {
    /** A mapping from input name to value. */
    inputs: Record<string, unknown>;
    /** The name or ID of a workflow trigger to use for this execution. */
    trigger?: string | null;
    /** Optionally specify a release tag if you want to pin to a specific release of the Workflow Deployment */
    releaseTag?: string | null;
    /** Optionally include a unique identifier for tracking purposes. Must be unique within a given Workspace. */
    externalId?: string | null;
    /** Arbitrary JSON metadata associated with this request. Can be used to capture additional monitoring data such as user id, session id, etc. for future analysis. */
    metadata?: Record<string, unknown> | null;
    /** The ID of a previous workflow execution to reference for context. */
    previousExecutionId?: string | null;
}
