# This GitHub Action is managed by the Vellum SDK Generator Repo and copied into each SDK repository.
name: Auto-merge Release PRs

on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0"

      - name: Install dependencies
        run: npm install
        working-directory: ee/automation

      - name: Wait for checks and auto-merge
        env:
          VELLUM_AUTOMATION_APP_ID: ${{ secrets.VELLUM_AUTOMATION_APP_ID }}
          VELLUM_AUTOMATION_PRIVATE_KEY: ${{ secrets.VELLUM_AUTOMATION_PRIVATE_KEY }}
          VELLUM_AUTOMATION_INSTALLATION_ID: ${{ secrets.VELLUM_AUTOMATION_INSTALLATION_ID }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: npm run auto-merge
        working-directory: ee/automation
